-- 1. Chức năng
CREATE TABLE CHUC_NANG
(
    MaChucNang  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(255) NOT NULL
);

-- 2. Người dùng
CREATE TABLE NGUOI_DUNG
(
    MaNguoiDung   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen         NVARCHAR2(255)       NOT NULL,
    Email         VARCHAR2(100) UNIQUE NOT NULL,
    AnhDaiDienURL VARCHAR2(500),
    SoDienThoai   VARCHAR2(15) UNIQUE  NOT NULL,
    DaXacThuc     NUMBER(1) DEFAULT 0 NOT NULL CHECK (DaXacThuc IN (0, 1)),
    NgayTao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Địa điểm
CREATE TABLE DIA_DIEM
(
    MaDiaDiem     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDiaDiem    NVARCHAR2(255) NOT NULL,
    SucChua       NUMBER(6, 0)  DEFAULT 0 NOT NULL CHECK (SucChua >= 0),
    TinhThanh     NVARCHAR2(255) NOT NULL,
    PhuongXa      NVARCHAR2(255) NOT NULL,
    SoNhaTenDuong NVARCHAR2(255) NOT NULL
);

-- 4. Nhà tài trợ
CREATE TABLE NHA_TAI_TRO
(
    MaNhaTT  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhaTT NVARCHAR2(255) NOT NULL
);

-- 5. Nhóm quyền
CREATE TABLE NHOM_QUYEN
(
    MaNhomQuyen  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomQuyen NVARCHAR2(100) NOT NULL,
    MoTa         CLOB
);

-- 6. Nghệ sĩ
CREATE TABLE NGHE_SI
(
    MaNgheSi      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNgheSi     NVARCHAR2(255) NOT NULL,
    Email         VARCHAR2(100) UNIQUE,
    AnhDaiDienURL VARCHAR2(500),
    SoDienThoai   VARCHAR2(15) UNIQUE
);

-- 8. Tài khoản
CREATE TABLE TAI_KHOAN
(
    MaTaiKhoan         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDung        NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    TenDangNhap        VARCHAR2(100) UNIQUE NOT NULL,
    MatKhauMaHoa       VARCHAR2(255)        NOT NULL,
    TrangThai          NVARCHAR2(50) DEFAULT N'Hoạt động' NOT NULL CHECK (TrangThai IN (N'Hoạt động', N'Bị khóa', N'Bị cấm')),
    LanDangNhapCuoi    TIMESTAMP,
    DongYNhanMarketing NUMBER(1) DEFAULT 0 CHECK (DongYNhanMarketing IN (0, 1))
);

-- 9. Nhà tổ chức
CREATE TABLE NHA_TO_CHUC
(
    MaNhaToChuc      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDaiDien   NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenNhaToChuc     NVARCHAR2(255)      NOT NULL,
    MaSoThue         VARCHAR2(50) UNIQUE NOT NULL,
    ThongTinNganHang NVARCHAR2(255)      NOT NULL,
    EmailHoTro       VARCHAR2(100)
);

-- 10. Ví cá nhân
CREATE TABLE VI_CA_NHAN
(
    MaVi             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    SoDu             NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (SoDu >= 0),
    MatKhauThanhToan VARCHAR2(255)           NOT NULL,
    TrangThai        NVARCHAR2(50) DEFAULT N'Đang hoạt động' NOT NULL CHECK (TrangThai IN (N'Bị khóa', N'Đang hoạt động'))
);

-- 11. Mẫu chính sách hoàn tiền
CREATE TABLE MAU_CHINH_SACH_HOAN_TIEN
(
    MaChinhSachHT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan    NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenChinhSach  NVARCHAR2(255) NOT NULL,
    MoTa          CLOB
);

-- 12. Phạm vi quyền
CREATE TABLE PHAM_VI_QUYEN
(
    MaPhamVi   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChucNang NUMBER REFERENCES CHUC_NANG (MaChucNang),
    Them       NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Them BETWEEN 0 AND 1),
    Sua        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Sua BETWEEN 0 AND 1),
    Xoa        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Xoa BETWEEN 0 AND 1),
    Xem        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Xem BETWEEN 0 AND 1),
    XuatFile   NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (XuatFile BETWEEN 0 AND 1)
);

-- 13. Mã giảm giá

-- 14. Quy tắc hoàn tiền
CREATE TABLE QUY_TAC_HOAN_TIEN
(
    MaQuyTac         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChinhSachHT    NUMBER REFERENCES MAU_CHINH_SACH_HOAN_TIEN (MaChinhSachHT),
    SoGioTruocSuKien NUMBER(10) NOT NULL CHECK (SoGioTruocSuKien >= 0),
    TyLeHoanTien     NUMBER(5, 2) DEFAULT 0 NOT NULL CHECK (TyLeHoanTien BETWEEN 0 AND 100)
);

-- 15. Cấu hình nhóm quyền
CREATE TABLE CAU_HINH_NHOM_QUYEN
(
    MaNhomQuyen NUMBER REFERENCES NHOM_QUYEN (MaNhomQuyen),
    MaPhamVi    NUMBER REFERENCES PHAM_VI_QUYEN (MaPhamVi),
    PRIMARY KEY (MaNhomQuyen, MaPhamVi)
);

-- 16. Phân quyền nhóm
CREATE TABLE PHAN_QUYEN_NHOM
(
    MaTaiKhoan  NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaNhomQuyen NUMBER REFERENCES NHOM_QUYEN (MaNhomQuyen),
    PRIMARY KEY (MaTaiKhoan, MaNhomQuyen)
);

-- 17. Phân quyền tài khoản
CREATE TABLE PHAN_QUYEN_TAI_KHOAN
(
    MaTaiKhoan NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaPhamVi   NUMBER REFERENCES PHAM_VI_QUYEN (MaPhamVi),
    PRIMARY KEY (MaTaiKhoan, MaPhamVi)
);

-- 18. Sự kiện
CREATE TABLE SU_KIEN
(
    MaSuKien           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDiaDiem          NUMBER REFERENCES DIA_DIEM (MaDiaDiem),
    MaChinhSachHT      NUMBER REFERENCES MAU_CHINH_SACH_HOAN_TIEN (MaChinhSachHT),
    MaNhaToChuc        NUMBER REFERENCES NHA_TO_CHUC (MaNhaToChuc),
    MaNguoiTao         NUMBER REFERENCES TAI_KHOAN(MaTaiKhoan),
    TenSuKien          NVARCHAR2(255) NOT NULL,
    ThoiGianBD         TIMESTAMP      NOT NULL,
    ThoiGianKT         TIMESTAMP      NOT NULL,
    ThoiGianMoBanVe    TIMESTAMP      NOT NULL,
    ThoiGianNgungBanVe TIMESTAMP      NOT NULL,
    MoTa               CLOB,
    TrangThai          NVARCHAR2(50) DEFAULT N'Chờ phê duyệt' NOT NULL CHECK (TrangThai IN
                                            (N'Chờ phê duyệt', N'Sắp diễn ra', N'Đang diễn ra', N'Đã kết thúc', N'Đã hủy')),
    TyLeHoaHong        NUMBER(5, 2) DEFAULT 0 NOT NULL CHECK (TyLeHoaHong BETWEEN 0 AND 100),
    QuyDinhSuKien      CLOB,
    AnhBiaURL          NVARCHAR2(1000),
    PhanLoai           NVARCHAR2(50),
    LaSuKienNoiBat     NUMBER(1) DEFAULT 0,
    ANHTHUMBNAILURL    NVARCHAR2(1000),
    LyDoTuChoi NVARCHAR2(1000),
    CONSTRAINT CK_SK_TGSK CHECK (ThoiGianBD < ThoiGianKT),
    CONSTRAINT CK_SK_TGBV CHECK (ThoiGianMoBanVe < ThoiGianNgungBanVe),
    CONSTRAINT CK_SK_TGBV_TGBD CHECK (ThoiGianMoBanVe < ThoiGianBD),
    CONSTRAINT CK_SK_TGNBV_TGKT CHECK (ThoiGianNgungBanVe <= ThoiGianKT)
);

-- 7. Chiến dịch khuyến mãi
CREATE TABLE CHIEN_DICH_KHUYEN_MAI
(
    MaChienDich  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChienDich NVARCHAR2(255) NOT NULL,
    ThoiDiemBD   TIMESTAMP      NOT NULL,
    ThoiDiemKT   TIMESTAMP      NOT NULL,
    TrangThai    NVARCHAR2(50) DEFAULT N'Chưa diễn ra' NOT NULL CHECK (TrangThai IN (N'Chưa diễn ra', N'Đang diễn ra', N'Tạm dừng', N'Đã kết thúc')),
    MaSuKien NUMBER REFERENCES SU_KIEN (MaSuKien),
    CONSTRAINT CK_CHIEN_DICH_TIME CHECK (ThoiDiemBD < ThoiDiemKT)
);

CREATE TABLE MA_GIAM_GIA
(
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChienDich    NUMBER REFERENCES CHIEN_DICH_KHUYEN_MAI (MaChienDich),
    MaGiamGia      VARCHAR2(50) UNIQUE NOT NULL,
    LoaiGiam       NVARCHAR2(50) DEFAULT N'Theo phần trăm' NOT NULL CHECK (LoaiGiam IN (N'Theo phần trăm', N'Số tiền cố định')),
    SoLuongGiam    NUMBER(15, 2)       NOT NULL CHECK (SoLuongGiam >= 0),
    GiamToiDa      NUMBER(15, 2)       NOT NULL CHECK (GiamToiDa >= 0),
    LuotDungToiDa  NUMBER(10) NOT NULL CHECK (LuotDungToiDa >= 0),
    SoLuotDaSuDung NUMBER(10) DEFAULT 0 CHECK (SoLuotDaSuDung >= 0),
    CONSTRAINT CK_GIAM_GIA_LIMIT CHECK (SoLuotDaSuDung <= LuotDungToiDa),
    CONSTRAINT CK_LG_THEO_PHAN_TRAM CHECK ((LoaiGiam = N'Theo phần trăm' AND SoLuongGiam <= 100) OR
                                           LoaiGiam = N'Số tiền cố định' ),
    CONSTRAINT CK_GIAM_TOI_DA CHECK ((LoaiGiam = N'Số tiền cố định' AND SoLuongGiam <= GiamToiDa) OR LoaiGiam = N'Theo phần trăm')
);


-- 19. Tài trợ
CREATE TABLE TAI_TRO
(
    MaSuKien   NUMBER REFERENCES SU_KIEN (MaSuKien),
    MaNhaTT    NUMBER REFERENCES NHA_TAI_TRO (MaNhaTT),
    HangTaiTro NVARCHAR2(50) DEFAULT N'Đồng' NOT NULL CHECK (HangTaiTro IN (N'Đồng', N'Bạc', N'Vàng', N'Kim Cương')),
    PRIMARY KEY (MaSuKien, MaNhaTT)
);

-- 20. Tham gia
CREATE TABLE THAM_GIA
(
    MaNgheSi    NUMBER REFERENCES NGHE_SI (MaNgheSi),
    MaSuKien    NUMBER REFERENCES SU_KIEN (MaSuKien),
    VaiTroChinh NVARCHAR2(100),
    PRIMARY KEY (MaNgheSi, MaSuKien)
);

-- 21. Hạng vé
CREATE TABLE HANG_VE
(
    MaHangVe        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSuKien        NUMBER REFERENCES SU_KIEN (MaSuKien),
    TenHangVe       NVARCHAR2(100) NOT NULL,
    GiaNiemYet      NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (GiaNiemYet >= 0),
    TongSoLuong     NUMBER(10) CHECK (TongSoLuong >= 0),
    GioiHanMoiNguoi NUMBER(5) CHECK (GioiHanMoiNguoi >= 0),
    MoTa            CLOB
);

-- 22. Khu vực
CREATE TABLE KHU_VUC
(
    MaKhuVuc  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaHangVe  NUMBER REFERENCES HANG_VE (MaHangVe),
    TenKhuVuc NVARCHAR2(255) NOT NULL,
    SucChuaKV NUMBER(10)     NOT NULL CHECK (SucChuaKV >= 0),
    MoTaKV    CLOB
);

-- 23. Lịch diễn
CREATE TABLE LICH_DIEN
(
    MaLichDien        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLichDien       NVARCHAR2(255) NOT NULL,
    TrangThaiLichDien NVARCHAR2(50) DEFAULT N'Chưa diễn ra' NOT NULL CHECK (TrangThaiLichDien IN (N'Chưa diễn ra', N'Đang diễn ra', N'Đã kết thúc')),
    MaSuKien          NUMBER REFERENCES SU_KIEN (MaSuKien),
    ThoiGianBatDau    TIMESTAMP      NOT NULL,
    ThoiGianKetThuc   TIMESTAMP      NOT NULL,
    TrangThaiBanVe    NVARCHAR2(50) DEFAULT N'Còn vé' NOT NULL CHECK (TrangThaiBanVe IN (N'Còn vé', N'Hết vé')),
    CONSTRAINT CK_SUAT_DIEN_TIME CHECK (ThoiGianBatDau < ThoiGianKetThuc)
);

-- 24. Phân công sự kiện nhân viên
CREATE TABLE PHAN_CONG_SK_NV
(
    MaTaiKhoan NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaSuKien   NUMBER REFERENCES SU_KIEN (MaSuKien),
    PRIMARY KEY (MaTaiKhoan, MaSuKien)
);

-- 25. Đơn mua
CREATE TABLE DON_MUA
(
    MaDonMua            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan          NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaSuKien            NUMBER REFERENCES SU_KIEN (MaSuKien),
    ThoiDiemMua         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TongTien            NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (TongTien >= 0),
    TrangThaiThanhToan  NVARCHAR2(50) DEFAULT N'Chờ thanh toán' NOT NULL CHECK (TrangThaiThanhToan IN
                                             (N'Chờ thanh toán', N'Đã thanh toán', N'Đã hủy', N'Đã hoàn tiền', N'Đã hết hạn')),
    PhuongThucThanhToan NVARCHAR2(100)
);

-- 26. Ghế ngồi
CREATE TABLE GHE_NGOI
(
    MaGhe    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhuVuc NUMBER REFERENCES KHU_VUC (MaKhuVuc),
    ToaDo    VARCHAR2(100) NOT NULL,
    CONSTRAINT UNQ_GHE_KV UNIQUE (MaKhuVuc, ToaDo)
);

-- 27. Trạng thái ghế theo suất
CREATE TABLE TRANG_THAI_GHE_THEO_SUAT
(
    MaGhe          NUMBER REFERENCES GHE_NGOI (MaGhe),
    MaLichDien     NUMBER REFERENCES LICH_DIEN (MaLichDien),
    TrangThai      NVARCHAR2(50) DEFAULT N'Còn trống' NOT NULL CHECK (TrangThai IN (N'Còn trống', N'Đã đặt', N'Đang giữ chỗ')),
    MaTaiKhoan     NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    ThoiGianHetHan TIMESTAMP,
    PRIMARY KEY (MaGhe, MaLichDien)
);

-- 28. Áp dụng
CREATE TABLE AP_DUNG
(
    MaDonMua         NUMBER REFERENCES DON_MUA (MaDonMua),
    IDGiamGia        NUMBER REFERENCES MA_GIAM_GIA (ID),
    ThoiDiemApDung   TIMESTAMP DEFAULT CURRENT_TIMESTAMP         NOT NULL,
    SoTienGiamThucTe NUMBER(15, 2) CHECK (SoTienGiamThucTe >= 0) NOT NULL,
    PRIMARY KEY (MaDonMua, IDGiamGia)
);

-- 29. Giao dịch
CREATE TABLE GIAO_DICH
(
    MaGiaoDich       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua         NUMBER REFERENCES DON_MUA (MaDonMua),
    MaGiaoDichCongTT VARCHAR2(100),
    SoTien           NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (SoTien >= 0),
    TrangThai        NVARCHAR2(50) DEFAULT N'Chờ thanh toán' NOT NULL CHECK (TrangThai IN (N'Chờ thanh toán', N'Thành công', N'Thất bại')),
    MaLoi            VARCHAR2(50),
    DuLieuPhanHoi    CLOB,
    ThoiGianTao      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_MA_LOI_NOT_NULL CHECK (TrangThai <> N'Thất bại' OR MaLoi IS NOT NULL)
);

-- 30. Lịch sử biến động ví
CREATE TABLE LICH_SU_BIEN_DONG_VI
(
    MaBienDong         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaVi               NUMBER REFERENCES VI_CA_NHAN (MaVi),
    MaGiaoDichLienQuan NUMBER REFERENCES GIAO_DICH (MaGiaoDich),
    LoaiBienDong       NVARCHAR2(50) NOT NULL CHECK (LoaiBienDong IN (N'Tăng', N'Giảm')),
    SoTien             NUMBER(15, 2) CHECK (SoTien >= 0),
    NoiDung            NVARCHAR2(500),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 31. Vé
CREATE TABLE VE
(
    MaVe            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua        NUMBER REFERENCES DON_MUA (MaDonMua),
    MaHangVe        NUMBER REFERENCES HANG_VE (MaHangVe),
    MaKhuVuc        NUMBER REFERENCES KHU_VUC (MaKhuVuc),
    MaGhe           NUMBER REFERENCES GHE_NGOI (MaGhe),
    MaLichDien      NUMBER REFERENCES LICH_DIEN (MaLichDien),
    DaBanLai        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (DaBanLai IN (0, 1)),
    GiaBanLai       NUMBER(15, 2) CHECK (GiaBanLai > 0),
    LinkQRCode      VARCHAR2(500),
    TrangThaiVe     VARCHAR2(50) DEFAULT N'Hiệu lực' NOT NULL CHECK (TrangThaiVe IN (N'Chờ thanh toán', N'Hiệu lực', N'Đã Check-in', N'Đã hủy', N'Đã hoàn vé')),
    ThoiGianDaBan   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    ThoiGianCheckIn TIMESTAMP,
	  CONSTRAINT CK_VE CHECK (DaBanLai = 0 OR TrangThaiVe <> N'Chờ thanh toán'),
    CONSTRAINT CK_TGCKIN CHECK (TrangThaiVe <> N'Đã Check-in' OR ThoiGianCheckIn IS NOT NULL),
    CONSTRAINT CK_TGCKIN_TGDB CHECK (ThoiGianCheckIn >= ThoiGianDaBan)
);

-- 32. Nhật ký soát vé
CREATE TABLE NHAT_KY_SOAT_VE
(
    MaSoatVe        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan      NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaVe            NUMBER REFERENCES VE (MaVe),
    TrangThaiSoatVe NUMBER(1) DEFAULT 0 NOT NULL CHECK (TrangThaiSoatVe IN (0, 1)),
    ThoiGianQuetMa  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ThietBiQuet     VARCHAR2(255)                       NOT NULL
);

-- 33. Yêu cầu hỗ trợ
CREATE TABLE YEU_CAU_HO_TRO
(
    MaYeuCau       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua       NUMBER REFERENCES DON_MUA (MaDonMua),
    MaTaiKhoan     NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaNhanVienXuLy NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    LoaiYeuCau     NVARCHAR2(100) NOT NULL CHECK (LoaiYeuCau IN (N'Hoàn tiền', N'Lỗi thanh toán', N'Thay đổi thông tin', N'Lỗi vé', N'Khiếu nại', N'Khác')),
    NoiDung        CLOB,
    ThoiDiemYeuCau TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThaiXuLy  NVARCHAR2(50) DEFAULT N'Chờ phản hồi' NOT NULL CHECK (TrangThaiXuLy IN (N'Đang xử lý', N'Chờ phản hồi', N'Đã xử lý')),
    CONSTRAINT CK_YCHT_STAFF_DIFF CHECK (MaNhanVienXuLy IS NULL OR MaNhanVienXuLy <> MaTaiKhoan)
);

-- 34. Lịch sử quyết toán
CREATE TABLE LICH_SU_QUYET_TOAN
(
    MaQT             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNhaToChuc      NUMBER REFERENCES NHA_TO_CHUC (MaNhaToChuc),
    KyQT             VARCHAR2(100),
    NgayQuyetToan    DATE DEFAULT CURRENT_DATE NOT NULL,
    TongDoanhThu     NUMBER(15, 2) CHECK (TongDoanhThu >= 0),
    PhiNenTang       NUMBER(15, 2) CHECK (PhiNenTang >= 0),
    SoTienChuyen     NUMBER(15, 2) CHECK (SoTienChuyen >= 0),
    ChungTuThanhToan VARCHAR2(500),
    TrangThai        NVARCHAR2(50) DEFAULT N'Đang xử lý' NOT NULL CHECK (TrangThai IN (N'Đã xử lý', N'Đang xử lý', N'Đã hủy'))
);

-- 35. Nhật ký hệ thống
CREATE TABLE NHAT_KY_HE_THONG
(
    MaNhatKyHT       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    HanhDong         NVARCHAR2(100),
    TenBang          NVARCHAR2(50),
    MaDoiTuong       NUMBER,
    DuLieuCu         CLOB,
    DuLieuMoi        CLOB,
    LyDo             VARCHAR2(500),
    ThoiDiemThucHien TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 36. Nhật ký thông báo
CREATE TABLE NHAT_KY_THONG_BAO
(
    MaThongBao   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua     NUMBER REFERENCES DON_MUA (MaDonMua),
    MaTaiKhoan   NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    KenhGui      NVARCHAR2(50) NOT NULL CHECK (KenhGui IN ('EMAIL', 'SMS', 'ZALO')),
    NoiDung      CLOB,
    TrangThai    NVARCHAR2(50) DEFAULT N'Đã gửi' NOT NULL CHECK (TrangThai IN (N'Đã gửi', N'Thất bại', N'Đã nhận', N'Đã xem', N'Thành công')),
    ThoiDiemGui  TIMESTAMP NOT NULL,
    ThoiDiemNhan TIMESTAMP,
    CONSTRAINT CK_TDNHAN CHECK (ThoiDiemNhan >= ThoiDiemGui)
);

-- 37. Nhật ký đăng nhập
CREATE TABLE NHAT_KY_DANG_NHAP
(
    MaLog              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan         NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenDangNhapNhapVao VARCHAR2(100),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai          NVARCHAR2(50) NOT NULL CHECK(TrangThai IN (N'Thành công', N'Thất bại')),
    LyDoThatBai        VARCHAR2(255),
    DiaChiIP           VARCHAR2(45),
    UserAgent          VARCHAR2(500)
);

-- 38. TOKEN Tài khoản
CREATE TABLE TOKEN_TAI_KHOAN
(
    MaToken       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan    NUMBER NOT NULL,
    GiaTriToken   VARCHAR2(500) UNIQUE NOT NULL,
    ThoiDiemHetHan TIMESTAMP NOT NULL,
    ThoiDiemCap    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DaThuHoi      NUMBER(1) DEFAULT 0 NOT NULL CHECK (DaThuHoi IN (0, 1)),
    CONSTRAINT FK_TOKEN_TAI_KHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

-- 39. Sơ đồ sự kiện
CREATE TABLE SO_DO_SU_KIEN
(
    MaSoDo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSuKien    NUMBER REFERENCES SU_KIEN (MaSuKien),
    DuLieuCanvas CLOB,
    ThoiGianTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNQ_SODO_SUKIEN UNIQUE (MaSuKien)
);

-- 40. Khu vực sơ đồ
CREATE TABLE KHU_VUC_SO_DO
(
    MaKhuVucSoDo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSoDo       NUMBER REFERENCES SO_DO_SU_KIEN (MaSoDo),
    MaKhuVuc     NUMBER REFERENCES KHU_VUC (MaKhuVuc),
    TenHienThi   NVARCHAR2(255),
    LoaiHinhDang NVARCHAR2(50),
    MauSac       VARCHAR2(50),
    ThuocTinhJson CLOB,
    KichThuocFont NUMBER(5)
);

--41. Lịch sử hoàn tiền
CREATE TABLE LICH_SU_HOAN_TIEN (
    MaHoanTien    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaVe          NUMBER        NOT NULL REFERENCES VE(MaVe),
    MaSuKien      NUMBER        NOT NULL REFERENCES SU_KIEN(MaSuKien),
    MaTaiKhoan    NUMBER        NOT NULL REFERENCES TAI_KHOAN(MaTaiKhoan),
    SoTienHoan    NUMBER(15, 2) NOT NULL,
    LyDoHoan      VARCHAR2(500),
    LoaiHoan      VARCHAR2(100) DEFAULT 'Yêu cầu người dùng'
                  CHECK (LoaiHoan IN ('Yêu cầu người dùng', 'Hủy sự kiện')),
    ThoiDiemHoan  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- TRG_AP_DUNG_BIU_CHECK_THOIDIEMAPDUNG
CREATE OR REPLACE TRIGGER TRG_AP_DUNG_BIU_CHECK_THOIDIEMAPDUNG
BEFORE INSERT OR UPDATE OF ThoiDiemApDung ON AP_DUNG
FOR EACH ROW
DECLARE
    v_ThoiDiemBD CHIEN_DICH_KHUYEN_MAI.ThoiDiemBD%TYPE;
    v_ThoiDiemKT CHIEN_DICH_KHUYEN_MAI.ThoiDiemKT%TYPE;
BEGIN
    BEGIN
        SELECT DISTINCT ThoiDiemBD, ThoiDiemKT
        INTO v_ThoiDiemBD, v_ThoiDiemKT
        FROM CHIEN_DICH_KHUYEN_MAI CDKM
        JOIN MA_GIAM_GIA MGG ON MGG.MaChienDich = CDKM.MaChienDich
        WHERE ID = :NEW.IDGiamGia;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, N'Lỗi! Không tìm thấy thông tin Chiến dịch của Mã giảm giá này.');
    END;

    IF (:NEW.ThoiDiemApDung < v_ThoiDiemBD) OR (:NEW.ThoiDiemApDung > v_ThoiDiemKT) THEN
        RAISE_APPLICATION_ERROR(-20002, N'Lỗi! Thời điểm áp dụng phải nằm trong khoảng thời gian của chiến dịch khuyến mãi.');
    END IF;
END;
/

-- TRG_MA_GIAM_GIA_BU_CHECK_THOIDIEMAPDUNG
CREATE OR REPLACE TRIGGER TRG_MA_GIAM_GIA_BU_CHECK_THOIDIEMAPDUNG
BEFORE UPDATE OF MaChienDich ON MA_GIAM_GIA
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF (:NEW.MaChienDich <> :OLD.MaChienDich) THEN

        SELECT COUNT(*) INTO v_count
        FROM AP_DUNG AD
        JOIN CHIEN_DICH_KHUYEN_MAI C ON C.MaChienDich = :NEW.MaChienDich
        WHERE AD.IDGiamGia = :NEW.ID
          AND (AD.ThoiDiemApDung < C.ThoiDiemBD OR AD.ThoiDiemApDung > C.ThoiDiemKT);

        IF (v_count > 0) THEN
            RAISE_APPLICATION_ERROR(-20003, N'Lỗi: Không thể đổi chiến dịch! Mã này đã có lượt áp dụng nằm ngoài khung thời gian của chiến dịch mới.');
        END IF;
    END IF;
END;
/

-- TRG_CDKM_BU_CHECK_TIME_AD (trùng tên, xuất hiện 2 lần)
CREATE OR REPLACE TRIGGER TRG_CDKM_BU_CHECK_TIME_AD
BEFORE UPDATE OF ThoiDiemBD, ThoiDiemKT ON CHIEN_DICH_KHUYEN_MAI
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF (:NEW.ThoiDiemBD > :OLD.ThoiDiemBD) OR (:NEW.ThoiDiemKT < :OLD.ThoiDiemKT) THEN
        SELECT COUNT(*)
        INTO v_count
        FROM AP_DUNG AD
        JOIN MA_GIAM_GIA MGG ON AD.IDGiamGia = MGG.ID
        WHERE MGG.MaChienDich = :NEW.MaChienDich
          AND (AD.ThoiDiemApDung < :NEW.ThoiDiemBD OR AD.ThoiDiemApDung > :NEW.ThoiDiemKT);

        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20004, N'Lỗi: Không thể thu hẹp thời gian chiến dịch! Đã có khách hàng áp dụng mã khuyến mãi nằm ngoài khung thời gian mới này.');
        END IF;
    END IF;
END;
/

-- TRG_YEU_CAU_HO_TRO_CHECK_HOANTIEN
CREATE OR REPLACE TRIGGER TRG_YEU_CAU_HO_TRO_CHECK_HOANTIEN
    BEFORE INSERT OR UPDATE ON YEU_CAU_HO_TRO
    FOR EACH ROW
DECLARE
    v_ThoiGianBD          TIMESTAMP;
    v_MaChinhSachHT       NUMBER;
    v_SoGioTruocSuKien    QUY_TAC_HOAN_TIEN.SoGioTruocSuKien%type;
    v_TyLeHoanTienCaoNhat NUMBER;
    v_ThoiDiemYeuCau      TIMESTAMP;
BEGIN
    IF :NEW.LoaiYeuCau = N'Hoàn tiền' THEN
        v_ThoiDiemYeuCau := NVL(:NEW.ThoiDiemYeuCau, CURRENT_TIMESTAMP);
        :NEW.ThoiDiemYeuCau := v_ThoiDiemYeuCau;

        SELECT SK.ThoiGianBD, SK.MaChinhSachHT
        INTO v_ThoiGianBD, v_MaChinhSachHT
        FROM DON_MUA DM
        JOIN SU_KIEN SK ON DM.MaSuKien = SK.MaSuKien
        WHERE DM.MaDonMua = :NEW.MaDonMua;

        IF v_ThoiDiemYeuCau >= v_ThoiGianBD THEN
            v_SoGioTruocSuKien := 0;
        ELSE
            v_SoGioTruocSuKien := (EXTRACT(DAY FROM (v_ThoiGianBD - v_ThoiDiemYeuCau)) * 24)
                                + EXTRACT(HOUR FROM (v_ThoiGianBD - v_ThoiDiemYeuCau));
        END IF;

        SELECT NVL(MAX(TyLeHoanTien), 0)
        INTO v_TyLeHoanTienCaoNhat
        FROM QUY_TAC_HOAN_TIEN
        WHERE MaChinhSachHT = v_MaChinhSachHT
          AND SoGioTruocSuKien <= v_SoGioTruocSuKien;

        IF v_TyLeHoanTienCaoNhat = 0 THEN
            RAISE_APPLICATION_ERROR(-20005,
                N'LỖI: Đơn hàng này hiện không đủ điều kiện hoàn tiền theo quy định (Quá hạn hoặc chính sách không cho phép).');
        END IF;

    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20006, N'LỖI: Không tìm thấy thông tin đơn hàng hoặc chính sách hoàn tiền liên quan.');
END;
/

-- TRG_DON_MUA_BU_CHECK_HOANTIEN
CREATE OR REPLACE TRIGGER TRG_DON_MUA_BU_CHECK_HOANTIEN
    BEFORE UPDATE OF MaSuKien ON DON_MUA
    FOR EACH ROW
    DECLARE
    v_count NUMBER;
    BEGIN
        IF :NEW.MaSuKien <> :OLD.MaSuKien THEN
            SELECT COUNT(*)
            INTO v_count
            FROM YEU_CAU_HO_TRO Y
            WHERE Y.MaDonMua = :NEW.MaDonMua AND LoaiYeuCau = N'Hoàn tiền'
            AND NOT EXISTS (
                SELECT 1
                FROM SU_KIEN SK
                JOIN QUY_TAC_HOAN_TIEN QTHT on SK.MaChinhSachHT = QTHT.MaChinhSachHT
                WHERE SK.MaSuKien = :NEW.MaSuKien AND (CAST(SK.ThoiGianBD AS DATE) - CAST(Y.ThoiDiemYeuCau AS DATE)) * 24 >= QTHT.SoGioTruocSuKien AND QTHT.TyLeHoanTien > 0
            );
            IF v_count > 0 THEN
                RAISE_APPLICATION_ERROR(-20007, N'Lỗi yêu cầu hoàn tiền không thỏa quy tắc');
            end if;
        end if;
    end;
/

-- TRG_SU_KIEN_BU_CHECK_HOANTIEN
CREATE OR REPLACE TRIGGER TRG_SU_KIEN_BU_CHECK_HOANTIEN
    BEFORE UPDATE OF MaChinhSachHT, ThoiGianBD ON SU_KIEN
    FOR EACH ROW
DECLARE
    v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM YEU_CAU_HO_TRO Y
        JOIN DON_MUA DM ON Y.MaDonMua = DM.MaDonMua
        WHERE DM.MaSuKien = :NEW.MaSuKien AND LoaiYeuCau = N'Hoàn tiền' AND NOT EXISTS(
            SELECT 1
            FROM QUY_TAC_HOAN_TIEN Q
            WHERE Q.MaChinhSachHT = :NEW.MaChinhSachHT AND (CAST(:NEW.ThoiGianBD AS DATE) - CAST(Y.ThoiDiemYeuCau AS DATE)) * 24 >= Q.SoGioTruocSuKien AND Q.TyLeHoanTien > 0
        );
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20008, N'Lỗi yêu cầu hoàn tiền không thỏa quy tắc');
        end if;
    end;
/

-- TRG_QTHT_BU_CHECK_HOANTIEN
CREATE OR REPLACE TRIGGER TRG_QTHT_BU_CHECK_HOANTIEN
    BEFORE UPDATE OF SoGioTruocSuKien ON QUY_TAC_HOAN_TIEN
    FOR EACH ROW
    WHEN (NEW.SoGioTruocSuKien > OLD.SoGioTruocSuKien)
DECLARE
    v_invalid_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_invalid_count
    FROM YEU_CAU_HO_TRO Y
    JOIN DON_MUA DM ON Y.MaDonMua = DM.MaDonMua
    JOIN SU_KIEN SK ON DM.MaSuKien = SK.MaSuKien
    WHERE SK.MaChinhSachHT = :NEW.MaChinhSachHT AND Y.LoaiYeuCau = N'Hoàn tiền' AND (CAST(SK.ThoiGianBD AS DATE) - CAST(Y.ThoiDiemYeuCau AS DATE)) * 24 >= :OLD.SoGioTruocSuKien AND (CAST(SK.ThoiGianBD AS DATE) - CAST(Y.ThoiDiemYeuCau AS DATE)) * 24 < :NEW.SoGioTruocSuKien;

    IF v_invalid_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20009, N'LỖI: Không thể tăng số giờ quy định vì sẽ làm ' || v_invalid_count || N' yêu cầu hoàn tiền hiện tại trở thành không hợp lệ.');
    END IF;
END;
/

-- TRG_LICH_DIEN_BIU_CHECK_THOI_GIAN
CREATE OR REPLACE TRIGGER TRG_LICH_DIEN_BIU_CHECK_THOI_GIAN
    BEFORE INSERT OR UPDATE ON LICH_DIEN
    FOR EACH ROW
DECLARE
    v_ThoiGianBD_SuKien SU_KIEN.ThoiGianBD%TYPE;
    v_ThoiGianKT_SuKien SU_KIEN.ThoiGianKT%TYPE;
BEGIN
    IF INSERTING
       OR (UPDATING AND (
           :NEW.ThoiGianBatDau <> :OLD.ThoiGianBatDau
           OR :NEW.ThoiGianKetThuc <> :OLD.ThoiGianKetThuc
           OR :NEW.MaSuKien <> :OLD.MaSuKien
       ))
    THEN
        SELECT ThoiGianBD, ThoiGianKT
        INTO v_ThoiGianBD_SuKien, v_ThoiGianKT_SuKien
        FROM SU_KIEN
        WHERE MaSuKien = :NEW.MaSuKien;

        IF :NEW.ThoiGianBatDau < v_ThoiGianBD_SuKien THEN
            RAISE_APPLICATION_ERROR(-20010, N'Lỗi: Thời gian bắt đầu suất diễn không được sớm hơn thời gian bắt đầu của sự kiện');
        END IF;

        IF :NEW.ThoiGianKetThuc > v_ThoiGianKT_SuKien THEN
            RAISE_APPLICATION_ERROR(-20011, N'Lỗi: Thời gian kết thúc suất diễn không được trễ hơn thời gian kết thúc của sự kiện');
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20012, N'Lỗi: Không tìm thấy thông tin sự kiện cha có mã ' || :NEW.MaSuKien);
END;
/

-- TRG_CDKM_BU_CHECK_TIME_AD (trùng tên lần 2)
CREATE OR REPLACE TRIGGER TRG_CDKM_BU_CHECK_TIME_AD
BEFORE UPDATE OF ThoiDiemBD, ThoiDiemKT ON CHIEN_DICH_KHUYEN_MAI
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF (:NEW.ThoiDiemBD > :OLD.ThoiDiemBD) OR (:NEW.ThoiDiemKT < :OLD.ThoiDiemKT) THEN
        SELECT COUNT(*)
        INTO v_count
        FROM AP_DUNG AD
        JOIN MA_GIAM_GIA MGG ON AD.IDGiamGia = MGG.ID
        WHERE MGG.MaChienDich = :NEW.MaChienDich
          AND (AD.ThoiDiemApDung < :NEW.ThoiDiemBD OR AD.ThoiDiemApDung > :NEW.ThoiDiemKT);

        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20013, N'Lỗi: Không thể thu hẹp thời gian chiến dịch! Đã có khách hàng áp dụng mã khuyến mãi nằm ngoài khung thời gian mới này.');
        END IF;
    END IF;
END;
/

-- TRG_VE_BIU_CHECK_THOIGIANCHECKIN
CREATE OR REPLACE TRIGGER TRG_VE_BIU_CHECK_THOIGIANCHECKIN
BEFORE INSERT OR UPDATE ON VE
FOR EACH ROW
DECLARE
    v_ThoiGianKT LICH_DIEN.ThoiGianKetThuc%TYPE;
BEGIN
    IF :NEW.ThoiGianCheckIn IS NOT NULL THEN
        IF INSERTING
           OR (UPDATING AND (
               :NEW.ThoiGianCheckIn <> NVL(:OLD.ThoiGianCheckIn, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
               OR :NEW.MaLichDien <> :OLD.MaLichDien
           ))
        THEN
            BEGIN
                SELECT ThoiGianKetThuc
                INTO v_ThoiGianKT
                FROM LICH_DIEN
                WHERE MaLichDien = :NEW.MaLichDien;

                IF :NEW.ThoiGianCheckIn > v_ThoiGianKT THEN
                    RAISE_APPLICATION_ERROR(-20014, N'Lỗi: Thời gian Check-in vé không được vượt quá thời gian kết thúc của Lịch diễn.');
                END IF;

            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    RAISE_APPLICATION_ERROR(-20015, N'Lỗi: Không tìm thấy lịch diễn có mã ' || :NEW.MaLichDien);
            END;
        END IF;
    END IF;
END;
/

-- TRG_LICH_DIEN_BU_CHECK_THOIGIANCHECKIN
CREATE OR REPLACE TRIGGER TRG_LICH_DIEN_BU_CHECK_THOIGIANCHECKIN
BEFORE UPDATE OF ThoiGianKetThuc ON LICH_DIEN
FOR EACH ROW
DECLARE
    v_count_vi_pham NUMBER;
BEGIN
    IF :NEW.ThoiGianKetThuc < :OLD.ThoiGianKetThuc THEN
        SELECT COUNT(*)
        INTO v_count_vi_pham
        FROM VE
        WHERE MaLichDien = :NEW.MaLichDien
          AND ThoiGianCheckIn > :NEW.ThoiGianKetThuc;

        IF (v_count_vi_pham > 0) THEN
            RAISE_APPLICATION_ERROR(-20016, N'Lỗi: Không thể rút ngắn thời gian! Có ' || v_count_vi_pham || N' vé đã check-in sau thời điểm kết thúc mới dự kiến.');
        END IF;
    END IF;
END;
/

-- TRG_DON_MUA_AU_UPDATE_TRANGTHAITHANHTOAN_DAHUY
CREATE OR REPLACE TRIGGER TRG_DON_MUA_AU_UPDATE_TRANGTHAITHANHTOAN_DAHUY
AFTER UPDATE OF TrangThaiThanhToan ON DON_MUA
FOR EACH ROW
BEGIN
    IF (:NEW.TrangThaiThanhToan = N'Đã hủy' OR :NEW.TrangThaiThanhToan = N'Đã hoàn tiền') AND (:OLD.TrangThaiThanhToan <> N'Đã hủy' AND :OLD.TrangThaiThanhToan <> N'Đã hoàn tiền') THEN
        UPDATE VE
        SET TrangThaiVe = N'Đã hủy'
        WHERE MaDonMua = :NEW.MaDonMua;
    END IF;
END;
/

-- TRG_VE_BIU_UPDATE_TRANGTHAITHANHTOAN_DAHUY
CREATE OR REPLACE TRIGGER TRG_VE_BIU_UPDATE_TRANGTHAITHANHTOAN_DAHUY
BEFORE INSERT OR UPDATE OF MaDonMua, TrangThaiVe ON VE
FOR EACH ROW
DECLARE
    v_TrangThaiThanhToan DON_MUA.TrangThaiThanhToan%TYPE;
BEGIN
    IF :NEW.TrangThaiVe <> N'Đã hủy' THEN
        BEGIN
            SELECT TrangThaiThanhToan INTO v_TrangThaiThanhToan
            FROM DON_MUA
            WHERE MaDonMua = :NEW.MaDonMua;

            IF v_TrangThaiThanhToan IN (N'Đã hủy', N'Đã hoàn tiền') THEN
                RAISE_APPLICATION_ERROR(-20017, N'Lỗi: Đơn mua đã bị hủy hoặc hoàn tiền. Trạng thái của vé thuộc đơn này bắt buộc phải là "Đã hủy".');
            END IF;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20018, N'Lỗi: Không tìm thấy Đơn mua cha.');
        END;
    END IF;
END;
/

-- TRG_VE_BU_UPDATE_TRANGTHAIVE_CHECKIN
CREATE OR REPLACE TRIGGER TRG_VE_BU_UPDATE_TRANGTHAIVE_CHECKIN
    BEFORE UPDATE OF TrangThaiVe, MaDonMua ON VE
    FOR EACH ROW
DECLARE
    v_TrangThaiThanhToan DON_MUA.TrangThaiThanhToan%TYPE;
BEGIN
    IF :NEW.TrangThaiVe = N'Đã Check-in' AND (:OLD.TrangThaiVe <> N'Đã Check-in' OR :NEW.MaDonMua <> :OLD.MaDonMua) THEN
        BEGIN
            SELECT TrangThaiThanhToan
            INTO v_TrangThaiThanhToan
            FROM DON_MUA
            WHERE MaDonMua = :NEW.MaDonMua;

            IF v_TrangThaiThanhToan <> N'Đã thanh toán' THEN
                RAISE_APPLICATION_ERROR(-20018, N'Lỗi: Vé chỉ được phép cập nhật thành "Đã Check-in" khi đơn mua chứa vé đó đã ở trạng thái "Đã thanh toán".');
            END IF;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20020, N'Lỗi: Không tìm thấy đơn mua chứa vé này trong hệ thống.');
        END;
    END IF;
END;
/

-- TRG_DON_MUA_BU_CHECK_CHECKIN
CREATE OR REPLACE TRIGGER TRG_DON_MUA_BU_CHECK_CHECKIN
    BEFORE UPDATE OF TrangThaiThanhToan ON DON_MUA
    FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.TrangThaiThanhToan <> N'Đã thanh toán' THEN

        SELECT COUNT(*)
        INTO v_count
        FROM VE
        WHERE MaDonMua = :NEW.MaDonMua AND TrangThaiVe = N'Đã Check-in';

        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20021, N'Lỗi: Đã có vé được check-in vào cổng. Không thể cập nhật đơn mua sang trạng thái khác "Đã thanh toán".');
        END IF;
    END IF;
END;
/

-- TRG_SUAT_DIEN_BIU_CHECK_KET_THUC
CREATE OR REPLACE TRIGGER TRG_SUAT_DIEN_BIU_CHECK_KET_THUC
    BEFORE INSERT OR UPDATE
    ON LICH_DIEN
    FOR EACH ROW
BEGIN
    IF :NEW.TrangThaiLichDien = N'Đã kết thúc' AND CURRENT_TIMESTAMP < :NEW.ThoiGianKetThuc THEN
        RAISE_APPLICATION_ERROR(-20022, N'Không thể kết thúc suất diễn khi chưa đến giờ kết thúc!');
    END IF;
END;
/

-- TRG_VE_BI_PREVENT_INSERTVE
CREATE OR REPLACE TRIGGER TRG_VE_BI_PREVENT_INSERTVE
    BEFORE INSERT OR UPDATE OF MaLichDien
    ON VE
    FOR EACH ROW
DECLARE
    v_trangthaibanve LICH_DIEN.TRANGTHAIBANVE%type;
BEGIN
    SELECT TRANGTHAIBANVE
    INTO v_trangthaibanve
    FROM LICH_DIEN
    WHERE MALICHDIEN = :NEW.MALICHDIEN;

    IF v_trangthaibanve = N'Hết vé' THEN
        RAISE_APPLICATION_ERROR(-20023, N'Đã hết vé cho lịch diễn này');
    end if;
end;
/

-- TRG_TRANG_THAI_GHE_THEO_SUAT_BIU_CHECK_TRANG_THAI_DA_DAT_VE
CREATE OR REPLACE TRIGGER TRG_TRANG_THAI_GHE_THEO_SUAT_BIU_CHECK_TRANG_THAI_DA_DAT_VE
    BEFORE INSERT OR UPDATE
    ON TRANG_THAI_GHE_THEO_SUAT
    FOR EACH ROW
DECLARE
    v_countVe NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_countVe
    FROM VE
    WHERE MaGhe = :NEW.MaGhe
      AND MaLichDien = :NEW.MaLichDien
      AND TrangThaiVe <> N'Đã hủy';

    IF v_countVe = 0 AND :NEW.TrangThai = N'Đã đặt' THEN
        RAISE_APPLICATION_ERROR(-20024,
            N'LỖI: Không thể chuyển trạng thái ghế sang Đã đặt vì chưa có bản ghi Vé đối chiếu hợp lệ.');
    END IF;
end;
/

-- TRG_DON_MUA_COMPOUND_UPDATEGHE
CREATE OR REPLACE TRIGGER TRG_DON_MUA_COMPOUND_UPDATEGHE
FOR UPDATE OF TrangThaiThanhToan ON DON_MUA
COMPOUND TRIGGER
    TYPE t_donmua_list IS TABLE OF DON_MUA.MaDonMua%TYPE;
    v_danh_sach_don t_donmua_list := t_donmua_list();
    BEFORE EACH ROW IS
    BEGIN
        IF (:NEW.TrangThaiThanhToan IN (N'Đã hủy', N'Đã hết hạn'))
           AND (:OLD.TrangThaiThanhToan NOT IN (N'Đã hủy', N'Đã hết hạn')) THEN

            v_danh_sach_don.EXTEND;
            v_danh_sach_don(v_danh_sach_don.LAST) := :NEW.MaDonMua;
        END IF;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS
    BEGIN
        IF v_danh_sach_don.COUNT > 0 THEN
            FOR i IN 1 .. v_danh_sach_don.COUNT LOOP
                UPDATE TRANG_THAI_GHE_THEO_SUAT
                SET TrangThai = N'Còn trống'
                WHERE (MaGhe, MaLichDien) IN (
                    SELECT MaGhe, MaLichDien
                    FROM VE
                    WHERE MaDonMua = v_danh_sach_don(i)
                ) AND TrangThai IN (N'Đang giữ chỗ', N'Đã đặt');
            END LOOP;

            v_danh_sach_don.DELETE;
        END IF;
    END AFTER STATEMENT;

END TRG_DON_MUA_COMPOUND_UPDATEGHE;
/

-- TRG_VE_BU_UPDATEGHE
CREATE OR REPLACE TRIGGER TRG_VE_BU_UPDATEGHE
    BEFORE UPDATE OF MaDonMua, MaGhe, MaLichDien ON VE
    FOR EACH ROW
    DECLARE
        v_trangThai DON_MUA.TrangThaiThanhToan%TYPE;
BEGIN
    SELECT TrangThaiThanhToan INTO v_trangThai
    FROM DON_MUA
    WHERE MaDonMua = :NEW.MaDonMua;

    IF v_trangThai IN (N'Đã hủy', N'Đã hết hạn') THEN
        RAISE_APPLICATION_ERROR(-20025, N'Lỗi, đơn mua đã hủy hoặc hết hạn thì ghế phải còn trống');
    end if;
END;
/

-- TRG_TRANG_THAI_GHE_THEO_SUAT_BU_UPDATEGHE
CREATE OR REPLACE TRIGGER TRG_TRANG_THAI_GHE_THEO_SUAT_BU_UPDATEGHE
    BEFORE UPDATE ON TRANG_THAI_GHE_THEO_SUAT
    FOR EACH ROW
    DECLARE
        v_count NUMBER;
BEGIN
    IF :NEW.TrangThai <> N'Còn trống' THEN
        SELECT COUNT(*) INTO v_count
        FROM DON_MUA DM
        JOIN VE V ON V.MADONMUA = DM.MADONMUA
        WHERE V.MaLichDien = :NEW.MaLichDien AND V.MaGhe = :NEW.MaGhe AND TrangThaiThanhToan IN (N'Đã hủy', N'Đã hết hạn') AND :NEW.TrangThai <> N'Còn trống';

        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20026, N'Lỗi, đơn mua đã hủy hoặc hết hạn thì ghế phải còn trống');
        end if;
    END IF;
END;
/

-- TRG_DON_MUA_BIU_CHECK_THOIDIEMMUA
CREATE OR REPLACE TRIGGER TRG_DON_MUA_BIU_CHECK_THOIDIEMMUA
    BEFORE INSERT OR UPDATE
    ON DON_MUA
    FOR EACH ROW
DECLARE
    v_thoi_gian_mo_ban    SU_KIEN.ThoiGianMoBanVe%type;
    v_thoi_gian_ngung_ban SU_KIEN.ThoiGianNgungBanVe%type;
BEGIN
    SELECT ThoiGianMoBanVe, ThoiGianNgungBanVe
    INTO v_thoi_gian_mo_ban, v_thoi_gian_ngung_ban
    FROM SU_KIEN
    WHERE MaSuKien = :NEW.MaSuKien;

    IF (:NEW.ThoiDiemMua < v_thoi_gian_mo_ban) OR (v_thoi_gian_ngung_ban < :NEW.ThoiDiemMua) THEN
        RAISE_APPLICATION_ERROR(-20027, N'Lỗi! Thời điểm mua phải nằm trong khoảng thời gian mở bán và ngưng bán vé của sự kiện. ');
    end if;
end;
/

-- TRG_SU_KIEN_BU_CHECK_THOIDIEMMUA
CREATE OR REPLACE TRIGGER TRG_SU_KIEN_BU_CHECK_THOIDIEMMUA
    BEFORE UPDATE
    ON SU_KIEN
    FOR EACH ROW
DECLARE
    v_count    NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM DON_MUA
    WHERE MaSuKien = :NEW.MaSuKien AND (ThoiDiemMua < :NEW.ThoiGianMoBanVe OR :NEW.ThoiGianNgungBanVe < ThoiDiemMua);

    IF (v_count > 0) THEN
        RAISE_APPLICATION_ERROR(-20028, N'Lỗi! Thời điểm mua phải nằm trong khoảng thời gian mở bán và ngưng bán vé của sự kiện. ');
    end if;
end;
/

-- TRG_AFTER_INSERT_LICH_DIEN
CREATE OR REPLACE TRIGGER TRG_AFTER_INSERT_LICH_DIEN
AFTER INSERT OR UPDATE ON LICH_DIEN
FOR EACH ROW
BEGIN
    INSERT INTO TRANG_THAI_GHE_THEO_SUAT (MaGhe, MaLichDien, TrangThai)
    SELECT g.MaGhe, :NEW.MaLichDien, N'Còn trống'
    FROM GHE_NGOI g
    JOIN KHU_VUC kv ON g.MaKhuVuc = kv.MaKhuVuc
    JOIN HANG_VE hv ON kv.MaHangVe = hv.MaHangVe
    WHERE hv.MaSuKien = :NEW.MaSuKien;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20029, N'Lỗi khi tự động sinh trạng thái ghế: ' || SQLERRM);
END;
/

-- Tổng tiền đơn hàng (DON_MUA.TongTien)
CREATE OR REPLACE PACKAGE PKG_BAO_MAT_DON_MUA AS
    g_ChoPhepUpdate BOOLEAN := FALSE;
END;
/

CREATE OR REPLACE TRIGGER TRG_DON_MUA_BU_CHAN_UPDATE
    BEFORE UPDATE OF TongTien ON DON_MUA
    FOR EACH ROW
BEGIN
    IF :NEW.TongTien <> :OLD.TongTien THEN
        IF NOT PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate THEN
            RAISE_APPLICATION_ERROR(-20030, N'LỖI BẢO MẬT: Cột Tổng Tiền được tính toán tự động, nghiêm cấm chỉnh sửa bằng tay!');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VE_BIUD_TINHTONGTIEN
    BEFORE INSERT OR UPDATE OF MaDonMua, MaHangVe OR DELETE ON VE
    FOR EACH ROW
DECLARE
    v_GiaCu NUMBER := 0;
    v_GiaMoi NUMBER := 0;
BEGIN
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := TRUE;
    
    -- Xử lý trường hợp mua lại vé (chuyển vé sang đơn mua mới)
    IF UPDATING AND :NEW.MaDonMua <> :OLD.MaDonMua AND :NEW.GiaBanLai IS NOT NULL AND :NEW.GiaBanLai > 0 THEN
        v_GiaMoi := :NEW.GiaBanLai;
        
        -- Chỉ cộng tiền vào đơn mua mới
        UPDATE DON_MUA SET TongTien = TongTien + v_GiaMoi WHERE MaDonMua = :NEW.MaDonMua;
        
        -- Đặt lại trạng thái vé
        :NEW.DaBanLai := 0;
        :NEW.GiaBanLai := NULL;
        
        -- KHÔNG trừ tiền của đơn mua cũ để giữ nguyên doanh thu quyết toán
    ELSE
        -- Logic cũ cho các trường hợp thêm/xóa/sửa bình thường
        IF DELETING OR UPDATING THEN
            SELECT GiaNiemYet INTO v_GiaCu FROM HANG_VE WHERE MaHangVe = :OLD.MaHangVe;
            UPDATE DON_MUA SET TongTien = TongTien - v_GiaCu WHERE MaDonMua = :OLD.MaDonMua;
        END IF;

        IF INSERTING OR UPDATING THEN
            SELECT GiaNiemYet INTO v_GiaMoi FROM HANG_VE WHERE MaHangVe = :NEW.MaHangVe;
            UPDATE DON_MUA SET TongTien = TongTien + v_GiaMoi WHERE MaDonMua = :NEW.MaDonMua;
        END IF;
    END IF;
    
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
EXCEPTION
    WHEN OTHERS THEN
        PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER TRG_HANG_VE_BU_TINHTONGTIEN
    BEFORE UPDATE OF GiaNiemYet ON HANG_VE
    FOR EACH ROW
BEGIN
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := TRUE;
    IF :NEW.GiaNiemYet <> :OLD.GiaNiemYet THEN
        FOR rec IN (
            SELECT MaDonMua, COUNT(*) as SoLuong
            FROM VE
            WHERE MaHangVe = :NEW.MaHangVe
            GROUP BY MaDonMua
        )
        LOOP
            UPDATE DON_MUA
            SET TongTien = TongTien + (:NEW.GiaNiemYet - :OLD.GiaNiemYet) * rec.SoLuong
            WHERE MaDonMua = rec.MaDonMua;
        END LOOP;
    END IF;
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
EXCEPTION
    WHEN OTHERS THEN
        PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER TRG_AP_DUNG_BIUD_TINHTONGTIEN
    BEFORE INSERT OR UPDATE OF SoTienGiamThucTe, MaDonMua OR DELETE ON AP_DUNG
    FOR EACH ROW
BEGIN
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := TRUE;
    IF DELETING OR UPDATING THEN
        UPDATE DON_MUA
        SET TongTien = TongTien + :OLD.SoTienGiamThucTe
        WHERE MaDonMua = :OLD.MaDonMua;
    END IF;

    IF INSERTING OR UPDATING THEN
        UPDATE DON_MUA
        SET TongTien = TongTien - :NEW.SoTienGiamThucTe
        WHERE MaDonMua = :NEW.MaDonMua;
    END IF;
    PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
EXCEPTION
    WHEN OTHERS THEN
        PKG_BAO_MAT_DON_MUA.g_ChoPhepUpdate := FALSE;
        RAISE;
END;
/

-- Sức chứa địa điểm
CREATE OR REPLACE TRIGGER TRG_SU_KIEN_BU_KIEM_TRA_SUC_CHUA
    BEFORE UPDATE OF MaDiaDiem ON SU_KIEN
    FOR EACH ROW
DECLARE
    v_tong_hien_tai NUMBER;
    v_suc_chua_tong NUMBER;
BEGIN
    SELECT SucChua INTO v_suc_chua_tong
    FROM DIA_DIEM WHERE MaDiaDiem = :NEW.MaDiaDiem;

    SELECT NVL(SUM(SucChuaKV), 0) INTO v_tong_hien_tai
    FROM KHU_VUC KV
    JOIN HANG_VE HV ON KV.MaHangVe = HV.MaHangVe
    WHERE HV.MaSuKien = :NEW.MaSuKien;

    IF v_suc_chua_tong < v_tong_hien_tai THEN
        RAISE_APPLICATION_ERROR(-20031, N'LỖI: Địa điểm mới không đủ sức chứa cho các khu vực hiện tại của sự kiện!');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DIA_DIEM_BU_KIEM_TRA_SUC_CHUA
    BEFORE UPDATE OF SucChua ON DIA_DIEM
    FOR EACH ROW
BEGIN
    FOR rec IN (
        SELECT HV.MaSuKien, NVL(SUM(KV.SucChuaKV), 0) AS TongSucChuaEvent
        FROM SU_KIEN SK
        JOIN HANG_VE HV ON SK.MaSuKien = HV.MaSuKien
        JOIN KHU_VUC KV ON HV.MaHangVe = KV.MaHangVe
        WHERE SK.MaDiaDiem = :NEW.MaDiaDiem
        GROUP BY HV.MaSuKien
    )
    LOOP
        IF :NEW.SucChua < rec.TongSucChuaEvent THEN
            RAISE_APPLICATION_ERROR(-20032, N'LỖI: Không thể giảm sức chứa!');
        END IF;
    END LOOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_KHU_VUC_COMPOUND_SUC_CHUA
FOR INSERT OR UPDATE OF SucChuaKV, MaHangVe ON KHU_VUC
COMPOUND TRIGGER
    TYPE t_events IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_events t_events;

    BEFORE EACH ROW IS
        v_masukien NUMBER;
    BEGIN
        SELECT MaSuKien INTO v_masukien FROM HANG_VE WHERE MaHangVe = :NEW.MaHangVe;
        v_events(v_masukien) := 1;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_id_sukien NUMBER;
        v_suc_chua_dd NUMBER;
        v_tong_kv NUMBER;
    BEGIN
        v_id_sukien := v_events.FIRST;
        WHILE v_id_sukien IS NOT NULL LOOP
            SELECT DD.SucChua INTO v_suc_chua_dd
            FROM SU_KIEN SK JOIN DIA_DIEM DD ON SK.MaDiaDiem = DD.MaDiaDiem
            WHERE SK.MaSuKien = v_id_sukien;

            SELECT NVL(SUM(SucChuaKV), 0) INTO v_tong_kv
            FROM KHU_VUC K JOIN HANG_VE H ON K.MaHangVe = H.MaHangVe
            WHERE H.MaSuKien = v_id_sukien;

            IF v_tong_kv > v_suc_chua_dd THEN
                 RAISE_APPLICATION_ERROR(-20033, N'LỖI: Vượt quá sức chứa!');
            END IF;

            v_id_sukien := v_events.NEXT(v_id_sukien);
        END LOOP;
    END AFTER STATEMENT;

END TRG_KHU_VUC_COMPOUND_SUC_CHUA;
/

CREATE OR REPLACE TRIGGER TRG_HANG_VE_COMPOUND_SUC_CHUA
FOR UPDATE OF MaSuKien ON HANG_VE
COMPOUND TRIGGER
    TYPE t_event_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_events t_event_list;
    BEFORE EACH ROW IS
    BEGIN
        v_events(:NEW.MaSuKien) := 1;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS
        v_id_sukien NUMBER;
        v_suc_chua_tong NUMBER;
        v_tong_sk_dich NUMBER;
    BEGIN
        v_id_sukien := v_events.FIRST;
        WHILE v_id_sukien IS NOT NULL LOOP

            SELECT SUCCHUA INTO v_suc_chua_tong
            FROM SU_KIEN SK JOIN DIA_DIEM DD ON SK.MaDiaDiem = DD.MaDiaDiem
            WHERE SK.MASUKIEN = v_id_sukien;

            SELECT NVL(SUM(SucChuaKV), 0) INTO v_tong_sk_dich
            FROM KHU_VUC KV JOIN HANG_VE HV ON KV.MaHangVe = HV.MaHangVe
            WHERE HV.MaSuKien = v_id_sukien;

            IF v_tong_sk_dich > v_suc_chua_tong THEN
                RAISE_APPLICATION_ERROR(-20034, N'LỖI: Quá tải sức chứa!');
            END IF;

            v_id_sukien := v_events.NEXT(v_id_sukien);
        END LOOP;
    END AFTER STATEMENT;

END TRG_HANG_VE_COMPOUND_SUC_CHUA;
/

-- Số lượng vé
CREATE OR REPLACE TRIGGER TRG_VE_COMPOUND_CHECK_SL
FOR INSERT OR UPDATE OF MaHangVe ON VE
COMPOUND TRIGGER
    TYPE t_hangve IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_hangve_list t_hangve;

    BEFORE EACH ROW IS
    BEGIN
        v_hangve_list(:NEW.MaHangVe) := 1;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_id_hangve NUMBER;
        v_tong_so_luong NUMBER;
        v_count_ve NUMBER;
    BEGIN
        v_id_hangve := v_hangve_list.FIRST;
        WHILE v_id_hangve IS NOT NULL LOOP

            SELECT TongSoLuong INTO v_tong_so_luong
            FROM HANG_VE
            WHERE MaHangVe = v_id_hangve;

            IF v_tong_so_luong IS NOT NULL THEN
                SELECT COUNT(*) INTO v_count_ve
                FROM VE
                WHERE MaHangVe = v_id_hangve;

                IF v_count_ve > v_tong_so_luong THEN
                    RAISE_APPLICATION_ERROR(-20035, N'LỖI: Vượt số lượng vé!');
                END IF;
            END IF;

            v_id_hangve := v_hangve_list.NEXT(v_id_hangve);
        END LOOP;
    END AFTER STATEMENT;

END TRG_VE_COMPOUND_CHECK_SL;
/

CREATE OR REPLACE TRIGGER TRG_HANG_VE_BU_CHECK_SL
    BEFORE UPDATE OF TongSoLuong ON HANG_VE
    FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.TongSoLuong < :OLD.TongSoLuong THEN

        SELECT COUNT(*) INTO v_count
        FROM VE
        WHERE MaHangVe = :NEW.MaHangVe;

        IF v_count > :NEW.TongSoLuong THEN
            RAISE_APPLICATION_ERROR(-20036, N'LỖI: Không thể giảm số lượng!');
        END IF;
    END IF;
END;
/

-- Thống kê sử dụng mã
CREATE OR REPLACE PACKAGE PKG_BAO_MAT_MA_GIAM_GIA AS
    g_ChoPhepUpdate BOOLEAN := FALSE;
END;
/

CREATE OR REPLACE TRIGGER TRG_MA_GIAM_GIA_BU_CHAN_UPDATE
    BEFORE UPDATE OF SoLuotDaSuDung ON MA_GIAM_GIA
    FOR EACH ROW
BEGIN
    IF NOT PKG_BAO_MAT_MA_GIAM_GIA.g_ChoPhepUpdate THEN
        RAISE_APPLICATION_ERROR(-20037, N'LỖI BẢO MẬT!');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AP_DUNG_BIUD_TINHLUOTDUNG
    BEFORE INSERT OR UPDATE OF IDGiamGia OR DELETE ON AP_DUNG
    FOR EACH ROW
BEGIN
    PKG_BAO_MAT_MA_GIAM_GIA.g_ChoPhepUpdate := TRUE;

    IF DELETING OR UPDATING THEN
        UPDATE MA_GIAM_GIA
        SET SoLuotDaSuDung = SoLuotDaSuDung - 1
        WHERE ID = :OLD.IDGiamGia;
    END IF;

    IF INSERTING OR UPDATING THEN
        UPDATE MA_GIAM_GIA
        SET SoLuotDaSuDung = SoLuotDaSuDung + 1
        WHERE ID = :NEW.IDGiamGia;
    END IF;

    PKG_BAO_MAT_MA_GIAM_GIA.g_ChoPhepUpdate := FALSE;

EXCEPTION
    WHEN OTHERS THEN
        PKG_BAO_MAT_MA_GIAM_GIA.g_ChoPhepUpdate := FALSE;
        RAISE;
END;
/

-- Doanh thu quyết toán
CREATE OR REPLACE PACKAGE PKG_TONG_DOANH_THU_QUYET_TOAN AS
    g_DangDongBo BOOLEAN := FALSE;
END;
/

CREATE OR REPLACE TRIGGER TRG_LICH_SU_QUYET_TOAN_BIU_TONG_DOANH_THU
    BEFORE INSERT OR UPDATE OF MaNhaToChuc, KyQT, TongDoanhThu, PhiNenTang ON LICH_SU_QUYET_TOAN
    FOR EACH ROW
DECLARE
    v_TienChuyen NUMBER;
BEGIN
    IF UPDATING('TongDoanhThu') AND NOT PKG_TONG_DOANH_THU_QUYET_TOAN.g_DangDongBo THEN
        RAISE_APPLICATION_ERROR(-20038, N'LỖI!');
    END IF;

    IF INSERTING OR UPDATING('MaNhaToChuc') OR UPDATING('KyQT') THEN
        IF NOT PKG_TONG_DOANH_THU_QUYET_TOAN.g_DangDongBo THEN
            SELECT NVL(SUM(DM.TongTien), 0) INTO :NEW.TongDoanhThu
            FROM DON_MUA DM JOIN SU_KIEN SK ON DM.MaSuKien = SK.MaSuKien
            WHERE SK.MaNhaToChuc = :NEW.MaNhaToChuc
              AND DM.TrangThaiThanhToan = N'Đã thanh toán'
              AND DM.PhuongThucThanhToan NOT LIKE N'%Mua lại%'
              AND 'Tháng ' || TO_CHAR(DM.ThoiDiemMua, 'FMMM/YYYY') = :NEW.KyQT;
        END IF;
    END IF;

    v_TienChuyen := NVL(:NEW.TongDoanhThu, 0) - NVL(:NEW.PhiNenTang, 0);

    IF v_TienChuyen < 0 THEN
        :NEW.SoTienChuyen := 0;
        :NEW.PhiNenTang := NVL(:NEW.TongDoanhThu, 0);
    ELSE
        :NEW.SoTienChuyen := v_TienChuyen;
    END IF;
END;
/

-- Quyết toán
CREATE OR REPLACE TRIGGER TRG_LICH_SU_QUYET_TOAN_BIU_CHECK_SO_TIEN_CHUYEN
    BEFORE INSERT OR UPDATE
    ON LICH_SU_QUYET_TOAN
    FOR EACH ROW
BEGIN
    :NEW.SoTienChuyen := NVL(:NEW.TongDoanhThu, 0) - NVL(:NEW.PhiNenTang, 0);
END;
/

-- Giảm giá thực tế
CREATE OR REPLACE TRIGGER TRG_AP_DUNG_BIU_CHECK_SO_TIEN_GIAM
    BEFORE INSERT OR UPDATE
    ON AP_DUNG
    FOR EACH ROW
DECLARE
    v_TongTien DON_MUA.TongTien%TYPE;
BEGIN
    SELECT TongTien
    INTO v_TongTien
    FROM DON_MUA
    WHERE MaDonMua = :NEW.MaDonMua;

    IF :NEW.SoTienGiamThucTe > v_TongTien THEN
        RAISE_APPLICATION_ERROR(-20039, N'Tiền giảm không hợp lệ');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20040, N'Không tìm thấy đơn');
END;
/

CREATE OR REPLACE TRIGGER TRG_DM_BU_CHECK_GIAMGIA
    BEFORE UPDATE OF TongTien ON DON_MUA
    FOR EACH ROW
    WHEN (NEW.TongTien < OLD.TongTien)
DECLARE
    v_tong_giam NUMBER := 0;
BEGIN
    SELECT NVL(SUM(SoTienGiamThucTe), 0) INTO v_tong_giam
    FROM AP_DUNG
    WHERE MaDonMua = :NEW.MaDonMua;

    IF v_tong_giam > :NEW.TongTien THEN
        RAISE_APPLICATION_ERROR(-20041, N'Lỗi giảm giá');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_GIU_CHO_DAT_VE_NHIEU_GHE (
    p_MaTaiKhoan    IN TAI_KHOAN.MaTaiKhoan%TYPE,
    p_DanhSachMaGhe IN VARCHAR2, -- Backend phải truyền mảng JSON: '[12, 13, 14]'
    p_MaLichDien    IN LICH_DIEN.MaLichDien%TYPE,

    p_MaDonMua      OUT DON_MUA.MaDonMua%TYPE,
    p_KetQua        OUT NVARCHAR2
)
IS
    v_SoGheYeuCau NUMBER;
    v_SoGheTrong  NUMBER;
    v_MaSuKien    SU_KIEN.MaSuKien%TYPE;
    v_TongTien    DON_MUA.TongTien%TYPE;

    -- Khai báo Exception tranh chấp dữ liệu
    RESOURCE_BUSY EXCEPTION;
    PRAGMA EXCEPTION_INIT(RESOURCE_BUSY, -54);
BEGIN
    p_MaDonMua := NULL;

    -- 1. Đếm số ghế yêu cầu trực tiếp từ mảng JSON
    SELECT COUNT(*) INTO v_SoGheYeuCau
    FROM JSON_TABLE(p_DanhSachMaGhe, '$[*]' COLUMNS (MaGhe NUMBER PATH '$'));

    IF v_SoGheYeuCau = 0 THEN
        p_KetQua := N'Thất bại: Danh sách ghế trống hoặc sai định dạng JSON.';
        RETURN;
    END IF;

    -- 2. TÌM VÀ KHÓA TẤT CẢ CÁC GHẾ CÙNG LÚC
    -- nếu có ít nhất 1 ghế thoả ĐK nhưng bị khoá thì sẽ ra lỗi RESOURCE BUSY
    SELECT COUNT(*) INTO v_SoGheTrong
    FROM TRANG_THAI_GHE_THEO_SUAT
    WHERE MaLichDien = p_MaLichDien
      AND TrangThai = N'Còn trống'
      AND MaGhe IN (
          SELECT MaGhe FROM JSON_TABLE(p_DanhSachMaGhe, '$[*]' COLUMNS (MaGhe NUMBER PATH '$'))
      )
    FOR UPDATE NOWAIT;

    -- 3. ĐẢM BẢO TẤT CẢ GHẾ ĐỀU TRỐNG
    IF v_SoGheTrong < v_SoGheYeuCau THEN
        ROLLBACK;
        p_KetQua := N'Thất bại: Một hoặc nhiều ghế bạn chọn đã có người khác đặt. Vui lòng chọn lại!';
        RETURN;
    END IF;

    -- 4. TÍNH TỔNG TIỀN VÀ LẤY MÃ SỰ KIỆN
    SELECT SUM(hv.GiaNiemYet), MIN(ld.MaSuKien)
    INTO v_TongTien, v_MaSuKien
    FROM GHE_NGOI g
    JOIN KHU_VUC kv ON g.MaKhuVuc = kv.MaKhuVuc
    JOIN HANG_VE hv ON kv.MaHangVe = hv.MaHangVe
    JOIN LICH_DIEN ld ON ld.MaSuKien = hv.MaSuKien
    WHERE ld.MaLichDien = p_MaLichDien
      AND g.MaGhe IN (
          SELECT MaGhe FROM JSON_TABLE(p_DanhSachMaGhe, '$[*]' COLUMNS (MaGhe NUMBER PATH '$'))
      );

    -- 5. TẠO 1 ĐƠN MUA DUY NHẤT
    INSERT INTO DON_MUA (MaTaiKhoan, MaSuKien, TongTien, TrangThaiThanhToan)
    VALUES (p_MaTaiKhoan, v_MaSuKien, 0, N'Chờ thanh toán')
    RETURNING MaDonMua INTO p_MaDonMua;

    -- 6. CẬP NHẬT TRẠNG THÁI CHO TẤT CẢ CÁC GHẾ
    UPDATE TRANG_THAI_GHE_THEO_SUAT
    SET TrangThai = N'Đang giữ chỗ'
    WHERE MaLichDien = p_MaLichDien
      AND MaGhe IN (
          SELECT MaGhe FROM JSON_TABLE(p_DanhSachMaGhe, '$[*]' COLUMNS (MaGhe NUMBER PATH '$'))
      );

    -- 7. TẠO HÀNG LOẠT VÉ CHO ĐƠN MUA
    INSERT INTO VE (MaDonMua, MaHangVe, MaGhe, MaLichDien, TrangThaiVe)
    SELECT p_MaDonMua, kv.MaHangVe, g.MaGhe, p_MaLichDien, N'Chờ thanh toán'
    FROM GHE_NGOI g
    JOIN KHU_VUC kv ON g.MaKhuVuc = kv.MaKhuVuc
    WHERE g.MaGhe IN (
          SELECT MaGhe FROM JSON_TABLE(p_DanhSachMaGhe, '$[*]' COLUMNS (MaGhe NUMBER PATH '$'))
    );

    COMMIT;
    p_KetQua := N'Thành công: Đã giữ ' || v_SoGheYeuCau || N' chỗ thành công. Vui lòng thanh toán!';

EXCEPTION
    WHEN RESOURCE_BUSY THEN
        ROLLBACK;
        p_KetQua := N'Thất bại: Có người khác đang thao tác trên các ghế này. Vui lòng chọn lại!';
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_GIAI_PHONG_GHE (
    p_SoPhutHetHan IN NUMBER DEFAULT 10, -- Mặc định là 10 phút, có thể truyền tham số khác
    p_KetQua       OUT NVARCHAR2
)
IS
    -- Định nghĩa Cursor tìm các đơn hàng quá hạn và Khóa chúng lại.
    -- Kỹ thuật SKIP LOCKED giúp lờ đi các đơn hàng đang bị khóa bởi giao dịch thanh toán khác
    CURSOR cur_DonMuaQuaHan IS
        SELECT MaDonMua
        FROM DON_MUA
        WHERE TrangThaiThanhToan = N'Chờ thanh toán'
          AND ThoiDiemMua <= CURRENT_TIMESTAMP - NUMTODSINTERVAL(p_SoPhutHetHan, 'MINUTE')
        FOR UPDATE SKIP LOCKED;

    v_Count NUMBER := 0;
BEGIN
    -- Mở vòng lặp duyệt qua từng đơn hàng quá hạn tìm được
    FOR rec IN cur_DonMuaQuaHan LOOP

        -- 1. Giải phóng Ghế: Đưa trạng thái từ 'Đang giữ chỗ' về lại 'Còn trống'
        UPDATE TRANG_THAI_GHE_THEO_SUAT tt
        SET TrangThai = N'Còn trống'
        WHERE EXISTS (
            SELECT 1 FROM VE v
            WHERE v.MaDonMua = rec.MaDonMua
              AND v.MaGhe = tt.MaGhe
              AND v.MaLichDien = tt.MaLichDien
        );

        -- 2. Hủy Vé: Đổi vé từ 'Chờ thanh toán' sang 'Đã hủy'
        UPDATE VE
        SET TrangThaiVe = N'Đã hủy'
        WHERE MaDonMua = rec.MaDonMua;

        -- 3. Hủy Đơn Mua: Chuyển trạng thái đơn thành 'Đã hết hạn'
        UPDATE DON_MUA
        SET TrangThaiThanhToan = N'Đã hết hạn'
        WHERE CURRENT OF cur_DonMuaQuaHan; -- Cập nhật chính xác dòng đang được Cursor trỏ tới

        v_Count := v_Count + 1;
    END LOOP;

    -- Chốt toàn bộ thay đổi
    COMMIT;

    IF v_Count > 0 THEN
        p_KetQua := N'Thành công: Đã dọn dẹp và giải phóng ghế cho ' || v_Count || N' đơn hàng quá hạn.';
    ELSE
        p_KetQua := N'Hệ thống sạch sẽ: Không có đơn hàng nào quá hạn cần giải phóng.';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống khi dọn dẹp ghế: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_DANG_KY_TAI_KHOAN (
    p_HoTen        IN NGUOI_DUNG.HoTen%Type,
    p_Email        IN NGUOI_DUNG.Email%type,
    p_SoDienThoai  IN NGUOI_DUNG.SoDienThoai%type,
    p_TenDangNhap  IN TAI_KHOAN.TenDangNhap%type,
    p_MatKhauMaHoa IN TAI_KHOAN.MatKhauMaHoa%type,

    --- Output
    p_KetQua       OUT NVARCHAR2
)
IS
    v_MaNguoiDung NGUOI_DUNG.MaNguoiDung%TYPE;
    v_MaTaiKhoan  NUMBER;
    v_Count       NUMBER;
BEGIN
    -- 1. Kiểm tra các dữ liệu UNIQUE bằng COUNT (Dành cho các luồng xử lý thông thường)
    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE Email = p_Email;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Email này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE SoDienThoai = p_SoDienThoai;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Số điện thoại này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM TAI_KHOAN WHERE TenDangNhap = p_TenDangNhap;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Tên đăng nhập đã tồn tại. Vui lòng chọn tên khác.';
        RETURN;
    END IF;

    -- 2. Insert dữ liệu
    INSERT INTO NGUOI_DUNG (HoTen, Email, SoDienThoai)
    VALUES (p_HoTen, p_Email, p_SoDienThoai)
    RETURNING MaNguoiDung INTO v_MaNguoiDung;

    INSERT INTO TAI_KHOAN (MaNguoiDung, TenDangNhap, MatKhauMaHoa)
    VALUES (v_MaNguoiDung, p_TenDangNhap, p_MatKhauMaHoa)
    RETURNING MaTaiKhoan INTO v_MaTaiKhoan;

    -- Giả sử ID nhóm quyền "Khách hàng" là 1
    INSERT INTO PHAN_QUYEN_NHOM (MaTaiKhoan, MaNhomQuyen)
    VALUES (v_MaTaiKhoan, 1);

    INSERT INTO VI_CA_NHAN (MaTaiKhoan, SoDu, MatKhauThanhToan)
    VALUES (v_MaTaiKhoan, 0, p_MatKhauMaHoa);

    -- 4. Hoàn tất
    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    -- Bắt lỗi Race Condition (Nếu 2 request lọt qua vòng COUNT cùng lúc)
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        p_KetQua := N'Lỗi: Thông tin (Email, SĐT hoặc Tên đăng nhập) đã tồn tại trong hệ thống do có giao dịch đồng thời.';

    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

-- Thanh toán bằng ví cá nhân
CREATE OR REPLACE PROCEDURE SP_THANH_TOAN_VI (
    p_MaDonMua IN DON_MUA.MaDonMua%type,
    p_MaTaiKhoan IN TAI_KHOAN.MaTaiKhoan%type,
    p_MaKhauThanhToan IN VI_CA_NHAN.MatKhauThanhToan%type,

    p_KetQua OUT NVARCHAR2
)
IS
    v_SoDu VI_CA_NHAN.SODU%type;
    v_MaVi VI_CA_NHAN.MAVI%type;
    v_MaGiaoDich GIAO_DICH.MaGiaoDich%type;
    v_TongTienThanhToan DON_MUA.TongTien%type;

BEGIN
    -- 1. Lấy thông tin để so sánh kiểm tra
    -- Lấy thông tin mã ví, số dư
    -- (Trường hợp sai mật khẩu hay sao đó thì văng xuống expception)
    SELECT Mavi, SoDu INTO v_MaVi, v_SoDu
    FROM VI_CA_NHAN V
    WHERE V.MaTaiKhoan = p_MaTaiKhoan AND V.MatKhauThanhToan = p_MaKhauThanhToan;

    -- Lấy tổng tiền của đơn mua từ mã đơn mua đầu vào
    SELECT TongTien INTO v_TongTienThanhToan
    FROM DON_MUA DM
    WHERE DM.MaDonMua = p_MaDonMua AND TrangThaiThanhToan = 'Chờ thanh toán';

    -- 2 Kiểm tra số dư để xử lý thanh toán, cập nhật trạng thái cho các bảng
    IF v_SoDU >= v_TongTienThanhToan THEN

        -- Cập nhật số dư ví cá nhân
        UPDATE VI_CA_NHAN
        SET SoDu = SoDu - v_TongTienThanhToan
        WHERE MaVi = v_MaVi;

        -- Cập nhật trạng thái Đơn mua
        UPDATE DON_MUA
        SET TrangThaiThanhToan = N'Đã thanh toán',
            PhuongThucThanhToan = N'Ví cá nhân'
        WHERE MaDonMua = p_MaDonMua;

        -- Cập nhật trạng thái vé
        UPDATE VE
        SET VE.TRANGTHAIVE = N'Hiệu Lực'
        WHERE MaDonMua = p_MaDonMua;

        -- Cập nhật trạng thái giao dịch
        UPDATE GIAO_DICH
        SET TRANGTHAI = N'Thành Công'
        WHERE MaDonMua = p_MaDonMua AND TRANGTHAI = N'Chờ thanh toán'
        RETURNING MaGiaoDich INTO v_MaGiaoDich; -- Lấy mã giao dịch liên quan

        -- Ghi lại lịch sử biến động ví
        INSERT INTO LICH_SU_BIEN_DONG_VI (MAVI,MaGiaoDichLienQuan, LoaiBienDong, SOTIEN, NOIDUNG)
        VALUES(v_MaVi, v_MaGiaoDich, N'Giảm',v_TongTienThanhToan, '* Thanh Toán đơn mua ' || p_MaDonMua ||' *');

        p_KetQua := N'Thanh toán thành công !!';
        COMMIT;

    ELSE
        p_KetQua := N'Không đủ tiền trong ví cá nhân, thanh toán Thất Bại !!';
        ROLLBACK ;
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_KetQua := N'Lỗi: Sai mật khẩu ví, hoặc đơn mua không tồn tại /đã được thanh toán !!';
        ROLLBACK ;
    WHEN OTHERS THEN
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
        ROLLBACK ;
end;
/

CREATE OR REPLACE PROCEDURE SP_XAC_NHAN_TT_NGOAI (
    p_MaDonMua          IN DON_MUA.MaDonMua%TYPE,
    p_MaGiaoDichCongTT  IN GIAO_DICH.MaGiaoDichCongTT%TYPE,
    p_SoTienThucNhan    IN GIAO_DICH.SoTien%TYPE,
    p_PhuongThuc        IN DON_MUA.PhuongThucThanhToan%TYPE,
    p_TrangThaiGiaoDich IN GIAO_DICH.TrangThai%TYPE,
    p_MaLoi             IN GIAO_DICH.MaLoi%TYPE,
    p_DuLieuPhanHoi     IN GIAO_DICH.DuLieuPhanHoi%TYPE,

    -- OUTPUT
    p_KetQua            OUT NVARCHAR2
)
IS
    v_TongTienDon  DON_MUA.TongTien%TYPE;
    v_TrangThaiDon DON_MUA.TrangThaiThanhToan%TYPE;

    RESOURCE_BUSY EXCEPTION;
    PRAGMA EXCEPTION_INIT(RESOURCE_BUSY, -54);
BEGIN
    -- 1. KHÓA ĐƠN MUA (Chống Double Call)
    -- Giả sử MoMo gặp lag và bắn 2 request "Thành công" về server cùng lúc,
    -- thằng nào đến trước sẽ khóa dòng này, thằng đến sau sẽ văng lỗi RESOURCE_BUSY.
    SELECT TongTien, TrangThaiThanhToan INTO v_TongTienDon, v_TrangThaiDon
    FROM DON_MUA
    WHERE MaDonMua = p_MaDonMua
    FOR UPDATE NOWAIT;

    -- 2. KIỂM TRA TRẠNG THÁI HIỆN TẠI
    IF v_TrangThaiDon = N'Đã thanh toán' THEN
        ROLLBACK;
        p_KetQua := N'Bỏ qua: Đơn hàng này đã được xác nhận thanh toán trước đó.';
        RETURN;
    END IF;

    IF v_TrangThaiDon <> N'Chờ thanh toán' THEN
        ROLLBACK;
        p_KetQua := N'Thất bại: Đơn hàng đang ở trạng thái không hợp lệ (' || v_TrangThaiDon || ').';
        RETURN;
    END IF;

    -- 3. BẢO MẬT: CHỐNG GIAN LẬN SỐ TIỀN
    -- Hacker có thể đánh chặn request từ MoMo về Server và sửa số tiền. Ta phải check chéo!
    IF p_TrangThaiGiaoDich = N'Thành công' AND p_SoTienThucNhan <> v_TongTienDon THEN
        -- Tùy chọn: Gọi SP_LOG_LOI_GIAO_DICH() ở đây nếu muốn lưu vết hacker
        ROLLBACK;
        p_KetQua := N'CẢNH BÁO GIAN LẬN: Số tiền cổng thanh toán báo về không khớp với hóa đơn hệ thống!';
        RETURN;
    END IF;

    -- 4. GHI LOG GIAO DỊCH
    INSERT INTO GIAO_DICH (MaDonMua, MaGiaoDichCongTT, SoTien, TrangThai, MaLoi, DuLieuPhanHoi, ThoiGianTao)
    VALUES (p_MaDonMua, p_MaGiaoDichCongTT, p_SoTienThucNhan, p_TrangThaiGiaoDich, p_MaLoi, p_DuLieuPhanHoi, CURRENT_TIMESTAMP);

    -- 5. CHỐT ĐƠN & XUẤT VÉ (Chỉ làm khi Thành công)
    IF p_TrangThaiGiaoDich = N'Thành công' THEN

        -- Cập nhật Đơn Mua
        UPDATE DON_MUA
        SET TrangThaiThanhToan = N'Đã thanh toán', PhuongThucThanhToan = p_PhuongThuc
        WHERE MaDonMua = p_MaDonMua;

        -- Kích hoạt Vé
        UPDATE VE
        SET TrangThaiVe = N'Hiệu lực', ThoiGianDaBan = CURRENT_TIMESTAMP
        WHERE MaDonMua = p_MaDonMua;

        -- Chốt Ghế (Chuyển 'Đang giữ chỗ' -> 'Đã đặt')
        UPDATE TRANG_THAI_GHE_THEO_SUAT tt
        SET TrangThai = N'Đã đặt'
        WHERE EXISTS (
            SELECT 1 FROM VE v
            WHERE v.MaDonMua = p_MaDonMua
              AND v.MaGhe = tt.MaGhe
              AND v.MaLichDien = tt.MaLichDien
        );

        p_KetQua := N'Xác nhận Webhook: Thanh toán thành công, đã xuất vé!';

    ELSE
        -- Nếu giao dịch thất bại từ cổng (Khách hủy, hết tiền trong thẻ...)
        -- Ta ghi log xong thì thôi, để kệ đó cho Job tự động hủy đơn sau 10 phút.
        p_KetQua := N'Xác nhận Webhook: Ghi nhận giao dịch thất bại từ cổng thanh toán.';
    END IF;

    -- Giải phóng khóa và chốt dữ liệu
    COMMIT;

EXCEPTION
    WHEN RESOURCE_BUSY THEN
        ROLLBACK;
        p_KetQua := N'Thất bại: Đơn hàng đang được một luồng Webhook khác xử lý.';
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        p_KetQua := N'Thất bại: Không tìm thấy đơn mua số ' || p_MaDonMua;
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_QUET_MA_SOAT_VE (
    p_MaVe             IN VE.MaVe%type,
    p_MaTaiKhoanSoatVe IN TAI_KHOAN.MaTaiKhoan%type,
    p_ThietBiQuet      IN NHAT_KY_SOAT_VE.ThietBiQuet%type,

    -- OUTPUT
    p_KetQua           OUT NVARCHAR2
)
IS
BEGIN
    -- 1. Thử cập nhật trạng thái vé ngay lập tức (Chống Race Condition)
    UPDATE VE
    SET TrangThaiVe = N'Đã Check-in',
        ThoiGianCheckIn = CURRENT_TIMESTAMP
    WHERE MaVe = p_MaVe
      AND TrangThaiVe = N'Hiệu lực';

    -- 2. Kiểm tra xem có dòng nào thực sự được cập nhật không
    IF SQL%ROWCOUNT > 0 THEN
        -- Nếu > 0 tức là vé hợp lệ và đã được đổi trạng thái thành công
        INSERT INTO NHAT_KY_SOAT_VE (MaTaiKhoan, MaVe, TrangThaiSoatVe, ThietBiQuet)
        VALUES (p_MaTaiKhoanSoatVe, p_MaVe, 1, p_ThietBiQuet);

        p_KetQua := N'Check-in thành công!';
        COMMIT;
    ELSE
        -- Nếu = 0 tức là vé không tồn tại hoặc KHÔNG ở trạng thái 'Hiệu lực' (đã check-in/đã hủy)
        INSERT INTO NHAT_KY_SOAT_VE (MaTaiKhoan, MaVe, TrangThaiSoatVe, ThietBiQuet)
        VALUES (p_MaTaiKhoanSoatVe, p_MaVe, 0, p_ThietBiQuet);

        p_KetQua := N'Check-in thất bại (Vé không hợp lệ hoặc đã được sử dụng)!';
        COMMIT;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
        ROLLBACK; -- Chỉ Rollback khi thực sự có lỗi hệ thống (như đứt kết nối, lỗi bảng...)
END;
/

CREATE OR REPLACE PROCEDURE SP_GHI_LOG_THONG_BAO (
    p_MaTaiKhoan IN TAI_KHOAN.MaTaiKhoan%TYPE,
    p_MaDonMua   IN DON_MUA.MaDonMua%TYPE,
    p_KenhGui    IN NHAT_KY_THONG_BAO.KenhGui%TYPE,
    p_NoiDung    IN NHAT_KY_THONG_BAO.NoiDung%TYPE,
    p_TrangThai  IN NHAT_KY_THONG_BAO.TrangThai%TYPE,

    p_KetQua     OUT NVARCHAR2
)
IS
    -- 1. Yêu cầu Oracle tách lệnh INSERT này thành một giao dịch độc lập
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO NHAT_KY_THONG_BAO (
        MaDonMua, MaTaiKhoan, KenhGui, NoiDung, TrangThai, ThoiDiemGui
    ) VALUES (
        p_MaDonMua, p_MaTaiKhoan, p_KenhGui, p_NoiDung, p_TrangThai, CURRENT_TIMESTAMP
    );

    -- Chốt giao dịch độc lập này lại
    COMMIT;
    p_KetQua := N'Ghi log thông báo thành công.';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống khi ghi log (Nhưng luồng chính không bị ảnh hưởng): ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_GHI_LOG_DANG_NHAP (
    -- INPUT PARAMETERS
    p_MaTaiKhoan         IN TAI_KHOAN.MaTaiKhoan%TYPE,
    p_TenDangNhapNhapVao IN NHAT_KY_DANG_NHAP.TenDangNhapNhapVao%TYPE,
    p_TrangThai          IN NHAT_KY_DANG_NHAP.TrangThai%TYPE,
    p_LyDoThatBai        IN NHAT_KY_DANG_NHAP.LyDoThatBai%TYPE,
    p_DiaChiIP           IN NHAT_KY_DANG_NHAP.DiaChiIP%TYPE,
    p_UserAgent          IN NHAT_KY_DANG_NHAP.UserAgent%TYPE,

    -- OUTPUT PARAMETER
    p_KetQua             OUT NVARCHAR2
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO NHAT_KY_DANG_NHAP (
        MaTaiKhoan, TenDangNhapNhapVao, TrangThai, LyDoThatBai, DiaChiIP, UserAgent
        -- Cột MaLog và ThoiGian không cần truyền vì DB đã cấu hình Auto-increment và Default Current_Timestamp
    ) VALUES (
        p_MaTaiKhoan, p_TenDangNhapNhapVao, p_TrangThai, p_LyDoThatBai, p_DiaChiIP, p_UserAgent
    );

    COMMIT; -- Chốt giao dịch ghi log
    p_KetQua := N'Ghi log thành công.';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống khi ghi log: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_LOG_LOI_GIAO_DICH (
    p_MaDonMua IN DON_MUA.MaDonMua%TYPE,
    p_SoTien   IN GIAO_DICH.SoTien%TYPE,
    p_MaLoi    IN GIAO_DICH.MaLoi%TYPE
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO GIAO_DICH (MaDonMua, SoTien, TrangThai, MaLoi, ThoiGianTao)
    VALUES (p_MaDonMua, p_SoTien, N'Thất bại', p_MaLoi, CURRENT_TIMESTAMP);

    COMMIT;
END;
/

CREATE OR REPLACE FUNCTION FN_Check_Ma_Giam_Gia_Hop_Le (
		p_MaGiamGia IN MA_GIAM_GIA.MaGiamGia%Type
) RETURN NUMBER(1)
AS
		v_TrangThai CHIEN_DICH_KHUYEN_MAI.TrangThai%Type;
		v_SoLuongGiam MA_GIAM_GIA.SoLuongGiam%Type;
		v_LuotDungToiDa MA_GIAM_GIA.LuotDungToiDa%Type;
		v_ThoiDiemBD CHIEN_DICH_KHUYEN_MAI.ThoiDiemBD%Type;
		v_ThoiDiemKT CHIEN_DICH_KHUYEN_MAI.ThoiDiemKT%Type;
BEGIN
		SELECT TrangThai, SoLuongGiam, LuotDungToiDa, ThoiDiemBD, ThoiDiemKT
		INTO v_TrangThai, v_SoLuongGiam, v_LuotDungToiDa, v_ThoiDiemBD, v_ThoiDiemKT
		FROM CHIEN_DICH_KHUYEN_MAI c
		JOIN MA_GIAM_GIA m ON m.MaChienDich = c.MaChienDich
		WHERE MaGiamGia = p_MaGiamGia;

		IF (CURRENT_TIMESTAMP < v_ThoiDiemBD) THEN
				RETURN -1;
		ELSIF (CURRENT_TIMESTAMP >= v_ThoiDiemKT) THEN
				RETURN -2;
		ELSIF (v_SoLuongGiam >= v_LuotDungToiDa) THEN
				RETURN -3;
		END IF;

		IF (v_TrangThai <> N'Đang diễn ra') THEN
				RETURN 0;
		END IF;

		RETURN 1;
EXCEPTION
		WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20042, 'Lỗi: Không tìm thấy mã giảm giá');
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20043, 'Lỗi trong quá trình xác minh mã giảm giá hợp lệ: ' || SQLERRM);
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_Tinh_Tien_Giam_Gia (
    p_MaGiamGia IN MA_GIAM_GIA.MaGiamGia%TYPE,
    p_TongTien  IN DON_MUA.TongTien%TYPE
)
RETURN NUMBER
AS
    v_LoaiGiam    MA_GIAM_GIA.LoaiGiam%TYPE;
    v_SoLuongGiam MA_GIAM_GIA.SoLuongGiam%TYPE;
    v_GiamToiDa   MA_GIAM_GIA.GiamToiDa%TYPE;
BEGIN
    SELECT LoaiGiam, SoLuongGiam, GiamToiDa
    INTO v_LoaiGiam, v_SoLuongGiam, v_GiamToiDa
    FROM MA_GIAM_GIA
    WHERE MaGiamGia = p_MaGiamGia; -- Thêm dấu ;

    IF v_LoaiGiam = N'Theo phần trăm' THEN
        -- Dùng LEAST thay vì MIN để lấy giá trị nhỏ hơn giữa mức giảm tối đa và số tiền % tính ra
        RETURN LEAST(v_GiamToiDa, p_TongTien * (v_SoLuongGiam / 100));
    ELSE
        RETURN LEAST(v_SoLuongGiam, p_TongTien);
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20044, 'Lỗi: Không tìm thấy mã giảm giá');
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20045, 'Lỗi hệ thống trong quá trình tính tiền giảm giá: ' || SQLERRM);
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_Kiem_Tra_Quyen_TK (
    p_MaTaiKhoan IN TAI_KHOAN.MaTaiKhoan%TYPE,
    p_MaChucNang IN CHUC_NANG.MaChucNang%TYPE,
    p_HanhDong   IN VARCHAR2 -- Nhận các giá trị: 'THEM', 'SUA', 'XOA', 'XEM', 'XUATFILE'
) RETURN NUMBER
AS
    v_CoQuyen NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_CoQuyen
    FROM PHAM_VI_QUYEN pv
    WHERE pv.MaChucNang = p_MaChucNang
      -- 1. Kiểm tra hành động người dùng yêu cầu có được phép (bằng 1) trong phạm vi quyền này không
      AND (
           (UPPER(p_HanhDong) = 'THEM' AND pv.Them = 1) OR
           (UPPER(p_HanhDong) = 'SUA' AND pv.Sua = 1) OR
           (UPPER(p_HanhDong) = 'XOA' AND pv.Xoa = 1) OR
           (UPPER(p_HanhDong) = 'XEM' AND pv.Xem = 1) OR
           (UPPER(p_HanhDong) = 'XUATFILE' AND pv.XuatFile = 1)
      )
      -- 2. Kiểm tra xem phạm vi quyền này có được gắn với người dùng qua đường trực tiếp hoặc qua nhóm không
      AND (
           -- Con đường A: Quyền được cấp trực tiếp cho tài khoản
           EXISTS (
               SELECT 1
               FROM PHAN_QUYEN_TAI_KHOAN pqt
               WHERE pqt.MaPhamVi = pv.MaPhamVi
                 AND pqt.MaTaiKhoan = p_MaTaiKhoan
           )
           OR
           -- Con đường B: Quyền được cấp thông qua nhóm quyền
           EXISTS (
               SELECT 1
               FROM CAU_HINH_NHOM_QUYEN ch
               JOIN PHAN_QUYEN_NHOM pqn ON ch.MaNhomQuyen = pqn.MaNhomQuyen
               WHERE ch.MaPhamVi = pv.MaPhamVi
                 AND pqn.MaTaiKhoan = p_MaTaiKhoan
           )
      );

    -- Nếu tìm thấy ít nhất 1 dòng thỏa mãn (từ nhóm hoặc trực tiếp), trả về 1 (Cho phép)
    IF v_CoQuyen > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20046, 'Lỗi hệ thống khi kiểm tra phân quyền: ' || SQLERRM);
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_LaySoVeConLai (
    p_MaHangVe IN HANG_VE.MaHangVe%TYPE
) RETURN NUMBER
AS
    v_TongSoLuong HANG_VE.TongSoLuong%TYPE;
    v_SoVeDaBan   NUMBER;
BEGIN
    SELECT TongSoLuong INTO v_TongSoLuong
    FROM HANG_VE
    WHERE MaHangVe = p_MaHangVe;

    SELECT COUNT(*) INTO v_SoVeDaBan
    FROM VE
    WHERE MaHangVe = p_MaHangVe
    AND TrangThaiVe IN (N'Hiệu lực', N'Đã Check-in');

    RETURN v_TongSoLuong - v_SoVeDaBan;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20047, 'Lỗi: Không tìm thấy hạng vé yêu cầu');
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20048, 'Có lỗi hệ thống trong quá trình tính số vé còn lại: ' || SQLERRM);
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_TinhPhiNenTang (
		p_MaSuKien IN SU_KIEN.MaSuKien%type,
		p_DoanhThu IN NUMBER
) RETURN NUMBER
AS
		v_TyLeHoaHong SU_KIEN.TyLeHoaHong%Type;
BEGIN
		SELECT TyLeHoaHong INTO v_TyLeHoaHong
		FROM SU_KIEN
		WHERE MaSuKien = p_MaSuKien;

		RETURN p_DoanhThu * v_TyLeHoaHong/100;
EXCEPTION
		WHEN NO_DATA_FOUND THEN
				RAISE_APPLICATION_ERROR(-20049, 'Loi: Khong tim thay su kien');
				RETURN 0;
		WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20050, 'Co loi trong qua trinh tinh phi nen tang: ' || SQLERRM);
				RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_TinhDoanhThuDuKien (
		p_MaSuKien SU_KIEN.MaSuKien%type
) RETURN NUMBER
AS
		v_TongDoanhThu NUMBER;
BEGIN
		SELECT NVL(SUM(TongTien),0) INTO v_TongDoanhThu
		FROM DON_MUA
		WHERE MaSuKien = p_MaSuKien
		AND TrangThaiThanhToan = N'Đã thanh toán';

		RETURN v_TongDoanhThu;
EXCEPTION
		WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20051, 'Co loi trong qua trinh tinh tong doanh thu su kien: ' || SQLERRM);
				RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_KiemTraGheTrong(
    p_MaGhe IN GHE_NGOI.MaGhe%TYPE,
    p_MaLichDien IN LICH_DIEN.MaLichDien%TYPE
)
RETURN NUMBER
AS
    v_Check_TonTai INT := 0;
    v_Check_GheTrong INT := 0;
BEGIN

    IF p_MaGhe IS NULL OR p_MaLichDien IS NULL THEN
        RAISE_APPLICATION_ERROR(-20052, N'Lỗi hệ thống: Mã ghế và mã lịch diễn không được để trống.');
    END IF;

    SELECT COUNT(*) INTO v_Check_TonTai
    FROM TRANG_THAI_GHE_THEO_SUAT
    WHERE MaGhe = p_MaGhe AND MaLichDien = p_MaLichDien;

    IF v_Check_TonTai = 0 THEN
         RAISE_APPLICATION_ERROR(-20053, N'Dữ liệu nhập vào không hợp lệ: Không tìm thấy thông tin ghế có ID [' || p_MaGhe || N'] cho lịch diễn có ID [' || p_MaLichDien || N'].');
    END IF;

    SELECT COUNT(*) INTO v_Check_GheTrong
    FROM TRANG_THAI_GHE_THEO_SUAT
    WHERE MaGhe = p_MaGhe AND MaLichDien = p_MaLichDien AND TrangThai = N'Còn trống';

    IF v_Check_GheTrong <> 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

CREATE OR REPLACE FUNCTION FN_TinhSoDuVi(
    p_MaVi VI_CA_NHAN.MAVI%type
) RETURN NUMBER AS
    v_SoDuHienTai NUMBER;
BEGIN
    SELECT NVL(SUM(
               CASE
                   WHEN LoaiBienDong = N'Tăng' THEN SoTien
                   WHEN LoaiBienDong = N'Giảm' THEN -SoTien
               END
               ), 0) INTO v_SoDuHienTai
    FROM LICH_SU_BIEN_DONG_VI
    WHERE MaVi = p_MaVi;
    RETURN v_SoDuHienTai;
end;
/

CREATE OR REPLACE FUNCTION FN_KiemTraGioiHanMuaVe(
    p_MaTaiKhoan TAI_KHOAN.MaTaiKhoan%TYPE,
    p_MaHangVe HANG_VE.MaHangVe%TYPE,
    p_SoVeDinhMua NUMBER
)
RETURN NUMBER
AS
    v_GioiHan HANG_VE.GioiHanMoiNguoi%TYPE;
    v_SoVeDaMua NUMBER;
BEGIN
    IF p_MaTaiKhoan IS NULL OR p_MaHangVe IS NULL THEN
        RAISE_APPLICATION_ERROR(-20054, N'Lỗi hệ thống: Mã tài khoản và mã hạng vé không được để trống.');
    END IF;

    SELECT GioiHanMoiNguoi INTO v_GioiHan
    FROM HANG_VE
    WHERE MaHangVe = p_MaHangVe;

    SELECT COUNT(MaVe) INTO v_SoVeDaMua
    FROM DON_MUA DM
    JOIN VE V
    ON DM.MaDonMua = V.MaDonMua
    WHERE DM.MaTaiKhoan = p_MaTaiKhoan AND V.MaHangVe = p_MaHangVe AND TrangThaiThanhToan IN ('Chờ thanh toán', 'Đã thanh toán');

    IF p_SoVeDinhMua + v_SoVeDaMua > v_GioiHan THEN
        RETURN 0;
    ELSE
        RETURN 1;
    END IF;
END;
/

INSERT INTO DIA_DIEM (TenDiaDiem, SucChua, TinhThanh, PhuongXa, SoNhaTenDuong)
VALUES ('Sân vận động Quốc gia Mỹ Đình', 40000, 'Hà Nội', 'Mỹ Đình 1', 'Đường Lê Đức Thọ, Nam Từ Liêm');

INSERT INTO NHOM_QUYEN (TenNhomQuyen, MoTa)
SELECT 'ROLE_CUSTOMER', 'Khách hàng - Quyền mua vé và xem sự kiện' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NHOM_QUYEN WHERE TenNhomQuyen = 'ROLE_CUSTOMER');

INSERT INTO NHOM_QUYEN (TenNhomQuyen, MoTa)
SELECT 'ROLE_ORGANIZER', 'Nhà tổ chức - Quyền tạo sự kiện và xem doanh thu' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NHOM_QUYEN WHERE TenNhomQuyen = 'ROLE_ORGANIZER');

INSERT INTO NHOM_QUYEN (TenNhomQuyen, MoTa)
SELECT 'ROLE_ADMIN', 'Quản trị viên - Quyền duyệt sự kiện và quản lý hệ thống' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NHOM_QUYEN WHERE TenNhomQuyen = 'ROLE_ADMIN');
COMMIT;

